// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mojo/document/document.proto

package document

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	core "github.com/mojo-lang/core/go/pkg/mojo/core"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ListAttribute_NumberStyle int32

const (
	ListAttribute_NUMBER_STYLE_UNSPECIFIED ListAttribute_NumberStyle = 0
	ListAttribute_NUMBER_STYLE_EXAMPLE     ListAttribute_NumberStyle = 1
	ListAttribute_NUMBER_STYLE_DECIMAL     ListAttribute_NumberStyle = 2
	ListAttribute_NUMBER_STYLE_LOWER_ROMAN ListAttribute_NumberStyle = 3
	ListAttribute_NUMBER_STYLE_UPPER_ROMAN ListAttribute_NumberStyle = 4
	ListAttribute_NUMBER_STYLE_LOWER_ALPHA ListAttribute_NumberStyle = 5
	ListAttribute_NUMBER_STYLE_UPPER_ALPHA ListAttribute_NumberStyle = 6
)

var ListAttribute_NumberStyle_name = map[int32]string{
	0: "NUMBER_STYLE_UNSPECIFIED",
	1: "NUMBER_STYLE_EXAMPLE",
	2: "NUMBER_STYLE_DECIMAL",
	3: "NUMBER_STYLE_LOWER_ROMAN",
	4: "NUMBER_STYLE_UPPER_ROMAN",
	5: "NUMBER_STYLE_LOWER_ALPHA",
	6: "NUMBER_STYLE_UPPER_ALPHA",
}

var ListAttribute_NumberStyle_value = map[string]int32{
	"NUMBER_STYLE_UNSPECIFIED": 0,
	"NUMBER_STYLE_EXAMPLE":     1,
	"NUMBER_STYLE_DECIMAL":     2,
	"NUMBER_STYLE_LOWER_ROMAN": 3,
	"NUMBER_STYLE_UPPER_ROMAN": 4,
	"NUMBER_STYLE_LOWER_ALPHA": 5,
	"NUMBER_STYLE_UPPER_ALPHA": 6,
}

func (x ListAttribute_NumberStyle) String() string {
	return proto.EnumName(ListAttribute_NumberStyle_name, int32(x))
}

func (ListAttribute_NumberStyle) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{8, 0}
}

type ListAttribute_NumberDelimiter int32

const (
	ListAttribute_NUMBER_DELIMITER_UNSPECIFIED ListAttribute_NumberDelimiter = 0
	ListAttribute_NUMBER_DELIMITER_PERIOD      ListAttribute_NumberDelimiter = 1
	ListAttribute_NUMBER_DELIMITER_ONE_PARENT  ListAttribute_NumberDelimiter = 2
	ListAttribute_NUMBER_DELIMITER_TWO_PARENTS ListAttribute_NumberDelimiter = 3
)

var ListAttribute_NumberDelimiter_name = map[int32]string{
	0: "NUMBER_DELIMITER_UNSPECIFIED",
	1: "NUMBER_DELIMITER_PERIOD",
	2: "NUMBER_DELIMITER_ONE_PARENT",
	3: "NUMBER_DELIMITER_TWO_PARENTS",
}

var ListAttribute_NumberDelimiter_value = map[string]int32{
	"NUMBER_DELIMITER_UNSPECIFIED": 0,
	"NUMBER_DELIMITER_PERIOD":      1,
	"NUMBER_DELIMITER_ONE_PARENT":  2,
	"NUMBER_DELIMITER_TWO_PARENTS": 3,
}

func (x ListAttribute_NumberDelimiter) String() string {
	return proto.EnumName(ListAttribute_NumberDelimiter_name, int32(x))
}

func (ListAttribute_NumberDelimiter) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{8, 1}
}

type Table_Alignment int32

const (
	Table_ALIGNMENT_UNSPECIFIED Table_Alignment = 0
	Table_ALIGNMENT_LEFT        Table_Alignment = 1
	Table_ALIGNMENT_RIGHT       Table_Alignment = 2
	Table_ALIGNMENT_CENTER      Table_Alignment = 3
)

var Table_Alignment_name = map[int32]string{
	0: "ALIGNMENT_UNSPECIFIED",
	1: "ALIGNMENT_LEFT",
	2: "ALIGNMENT_RIGHT",
	3: "ALIGNMENT_CENTER",
}

var Table_Alignment_value = map[string]int32{
	"ALIGNMENT_UNSPECIFIED": 0,
	"ALIGNMENT_LEFT":        1,
	"ALIGNMENT_RIGHT":       2,
	"ALIGNMENT_CENTER":      3,
}

func (x Table_Alignment) String() string {
	return proto.EnumName(Table_Alignment_name, int32(x))
}

func (Table_Alignment) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{13, 0}
}

type Quoted_Type int32

const (
	Quoted_TYPE_DOUBLE Quoted_Type = 0
	Quoted_TYPE_SINGLE Quoted_Type = 1
)

var Quoted_Type_name = map[int32]string{
	0: "TYPE_DOUBLE",
	1: "TYPE_SINGLE",
}

var Quoted_Type_value = map[string]int32{
	"TYPE_DOUBLE": 0,
	"TYPE_SINGLE": 1,
}

func (x Quoted_Type) String() string {
	return proto.EnumName(Quoted_Type_name, int32(x))
}

func (Quoted_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{27, 0}
}

type Citation_Mode int32

const (
	Citation_MODE_NORMAL          Citation_Mode = 0
	Citation_MODE_AUTHOR_IN_TEXT  Citation_Mode = 1
	Citation_MODE_SUPPRESS_AUTHOR Citation_Mode = 2
)

var Citation_Mode_name = map[int32]string{
	0: "MODE_NORMAL",
	1: "MODE_AUTHOR_IN_TEXT",
	2: "MODE_SUPPRESS_AUTHOR",
}

var Citation_Mode_value = map[string]int32{
	"MODE_NORMAL":          0,
	"MODE_AUTHOR_IN_TEXT":  1,
	"MODE_SUPPRESS_AUTHOR": 2,
}

func (x Citation_Mode) String() string {
	return proto.EnumName(Citation_Mode_name, int32(x))
}

func (Citation_Mode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{29, 0}
}

type Document struct {
	MetaData             *MetaData `protobuf:"bytes,1,opt,name=meta_data,json=metaData,proto3" json:"metaData,omitempty"`
	Blocks               []*Block  `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Document) Reset()         { *m = Document{} }
func (m *Document) String() string { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()    {}
func (*Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{0}
}
func (m *Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Document.Unmarshal(m, b)
}
func (m *Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Document.Marshal(b, m, deterministic)
}
func (m *Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Document.Merge(m, src)
}
func (m *Document) XXX_Size() int {
	return xxx_messageInfo_Document.Size(m)
}
func (m *Document) XXX_DiscardUnknown() {
	xxx_messageInfo_Document.DiscardUnknown(m)
}

var xxx_messageInfo_Document proto.InternalMessageInfo

func (m *Document) GetMetaData() *MetaData {
	if m != nil {
		return m.MetaData
	}
	return nil
}

func (m *Document) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type Block struct {
	// Types that are valid to be assigned to Block:
	//	*Block_Plain
	//	*Block_Paragraph
	//	*Block_LineBlock
	//	*Block_CodeBlock
	//	*Block_BlockQuote
	//	*Block_OrderedList
	//	*Block_BulletList
	//	*Block_DefinitionList
	//	*Block_Header
	//	*Block_Table
	//	*Block_Division
	Block                isBlock_Block `protobuf_oneof:"block"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{1}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

type isBlock_Block interface {
	isBlock_Block()
}

type Block_Plain struct {
	Plain *Plain `protobuf:"bytes,1,opt,name=plain,proto3,oneof" json:"plain,omitempty"`
}
type Block_Paragraph struct {
	Paragraph *Paragraph `protobuf:"bytes,2,opt,name=paragraph,proto3,oneof" json:"paragraph,omitempty"`
}
type Block_LineBlock struct {
	LineBlock *LineBlock `protobuf:"bytes,3,opt,name=line_block,json=lineBlock,proto3,oneof" json:"lineBlock,omitempty"`
}
type Block_CodeBlock struct {
	CodeBlock *CodeBlock `protobuf:"bytes,4,opt,name=code_block,json=codeBlock,proto3,oneof" json:"codeBlock,omitempty"`
}
type Block_BlockQuote struct {
	BlockQuote *BlockQuote `protobuf:"bytes,5,opt,name=block_quote,json=blockQuote,proto3,oneof" json:"blockQuote,omitempty"`
}
type Block_OrderedList struct {
	OrderedList *OrderedList `protobuf:"bytes,6,opt,name=ordered_list,json=orderedList,proto3,oneof" json:"orderedList,omitempty"`
}
type Block_BulletList struct {
	BulletList *BulletList `protobuf:"bytes,7,opt,name=bullet_list,json=bulletList,proto3,oneof" json:"bulletList,omitempty"`
}
type Block_DefinitionList struct {
	DefinitionList *DefinitionList `protobuf:"bytes,8,opt,name=definition_list,json=definitionList,proto3,oneof" json:"definitionList,omitempty"`
}
type Block_Header struct {
	Header *Header `protobuf:"bytes,9,opt,name=header,proto3,oneof" json:"header,omitempty"`
}
type Block_Table struct {
	Table *Table `protobuf:"bytes,10,opt,name=table,proto3,oneof" json:"table,omitempty"`
}
type Block_Division struct {
	Division *Division `protobuf:"bytes,11,opt,name=division,proto3,oneof" json:"division,omitempty"`
}

func (*Block_Plain) isBlock_Block()          {}
func (*Block_Paragraph) isBlock_Block()      {}
func (*Block_LineBlock) isBlock_Block()      {}
func (*Block_CodeBlock) isBlock_Block()      {}
func (*Block_BlockQuote) isBlock_Block()     {}
func (*Block_OrderedList) isBlock_Block()    {}
func (*Block_BulletList) isBlock_Block()     {}
func (*Block_DefinitionList) isBlock_Block() {}
func (*Block_Header) isBlock_Block()         {}
func (*Block_Table) isBlock_Block()          {}
func (*Block_Division) isBlock_Block()       {}

func (m *Block) GetBlock() isBlock_Block {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *Block) GetPlain() *Plain {
	if x, ok := m.GetBlock().(*Block_Plain); ok {
		return x.Plain
	}
	return nil
}

func (m *Block) GetParagraph() *Paragraph {
	if x, ok := m.GetBlock().(*Block_Paragraph); ok {
		return x.Paragraph
	}
	return nil
}

func (m *Block) GetLineBlock() *LineBlock {
	if x, ok := m.GetBlock().(*Block_LineBlock); ok {
		return x.LineBlock
	}
	return nil
}

func (m *Block) GetCodeBlock() *CodeBlock {
	if x, ok := m.GetBlock().(*Block_CodeBlock); ok {
		return x.CodeBlock
	}
	return nil
}

func (m *Block) GetBlockQuote() *BlockQuote {
	if x, ok := m.GetBlock().(*Block_BlockQuote); ok {
		return x.BlockQuote
	}
	return nil
}

func (m *Block) GetOrderedList() *OrderedList {
	if x, ok := m.GetBlock().(*Block_OrderedList); ok {
		return x.OrderedList
	}
	return nil
}

func (m *Block) GetBulletList() *BulletList {
	if x, ok := m.GetBlock().(*Block_BulletList); ok {
		return x.BulletList
	}
	return nil
}

func (m *Block) GetDefinitionList() *DefinitionList {
	if x, ok := m.GetBlock().(*Block_DefinitionList); ok {
		return x.DefinitionList
	}
	return nil
}

func (m *Block) GetHeader() *Header {
	if x, ok := m.GetBlock().(*Block_Header); ok {
		return x.Header
	}
	return nil
}

func (m *Block) GetTable() *Table {
	if x, ok := m.GetBlock().(*Block_Table); ok {
		return x.Table
	}
	return nil
}

func (m *Block) GetDivision() *Division {
	if x, ok := m.GetBlock().(*Block_Division); ok {
		return x.Division
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Block) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Block_Plain)(nil),
		(*Block_Paragraph)(nil),
		(*Block_LineBlock)(nil),
		(*Block_CodeBlock)(nil),
		(*Block_BlockQuote)(nil),
		(*Block_OrderedList)(nil),
		(*Block_BulletList)(nil),
		(*Block_DefinitionList)(nil),
		(*Block_Header)(nil),
		(*Block_Table)(nil),
		(*Block_Division)(nil),
	}
}

type Line struct {
	Values               []*Inline `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Line) Reset()         { *m = Line{} }
func (m *Line) String() string { return proto.CompactTextString(m) }
func (*Line) ProtoMessage()    {}
func (*Line) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{2}
}
func (m *Line) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Line.Unmarshal(m, b)
}
func (m *Line) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Line.Marshal(b, m, deterministic)
}
func (m *Line) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Line.Merge(m, src)
}
func (m *Line) XXX_Size() int {
	return xxx_messageInfo_Line.Size(m)
}
func (m *Line) XXX_DiscardUnknown() {
	xxx_messageInfo_Line.DiscardUnknown(m)
}

var xxx_messageInfo_Line proto.InternalMessageInfo

func (m *Line) GetValues() []*Inline {
	if m != nil {
		return m.Values
	}
	return nil
}

type Plain struct {
	Inlines              []*Inline `protobuf:"bytes,2,rep,name=inlines,proto3" json:"inlines,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Plain) Reset()         { *m = Plain{} }
func (m *Plain) String() string { return proto.CompactTextString(m) }
func (*Plain) ProtoMessage()    {}
func (*Plain) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{3}
}
func (m *Plain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plain.Unmarshal(m, b)
}
func (m *Plain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plain.Marshal(b, m, deterministic)
}
func (m *Plain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plain.Merge(m, src)
}
func (m *Plain) XXX_Size() int {
	return xxx_messageInfo_Plain.Size(m)
}
func (m *Plain) XXX_DiscardUnknown() {
	xxx_messageInfo_Plain.DiscardUnknown(m)
}

var xxx_messageInfo_Plain proto.InternalMessageInfo

func (m *Plain) GetInlines() []*Inline {
	if m != nil {
		return m.Inlines
	}
	return nil
}

type Paragraph struct {
	Inlines              []*Inline `protobuf:"bytes,2,rep,name=inlines,proto3" json:"inlines,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Paragraph) Reset()         { *m = Paragraph{} }
func (m *Paragraph) String() string { return proto.CompactTextString(m) }
func (*Paragraph) ProtoMessage()    {}
func (*Paragraph) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{4}
}
func (m *Paragraph) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Paragraph.Unmarshal(m, b)
}
func (m *Paragraph) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Paragraph.Marshal(b, m, deterministic)
}
func (m *Paragraph) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Paragraph.Merge(m, src)
}
func (m *Paragraph) XXX_Size() int {
	return xxx_messageInfo_Paragraph.Size(m)
}
func (m *Paragraph) XXX_DiscardUnknown() {
	xxx_messageInfo_Paragraph.DiscardUnknown(m)
}

var xxx_messageInfo_Paragraph proto.InternalMessageInfo

func (m *Paragraph) GetInlines() []*Inline {
	if m != nil {
		return m.Inlines
	}
	return nil
}

type LineBlock struct {
	Lines                []*Line  `protobuf:"bytes,2,rep,name=lines,proto3" json:"lines,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LineBlock) Reset()         { *m = LineBlock{} }
func (m *LineBlock) String() string { return proto.CompactTextString(m) }
func (*LineBlock) ProtoMessage()    {}
func (*LineBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{5}
}
func (m *LineBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LineBlock.Unmarshal(m, b)
}
func (m *LineBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LineBlock.Marshal(b, m, deterministic)
}
func (m *LineBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LineBlock.Merge(m, src)
}
func (m *LineBlock) XXX_Size() int {
	return xxx_messageInfo_LineBlock.Size(m)
}
func (m *LineBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_LineBlock.DiscardUnknown(m)
}

var xxx_messageInfo_LineBlock proto.InternalMessageInfo

func (m *LineBlock) GetLines() []*Line {
	if m != nil {
		return m.Lines
	}
	return nil
}

type CodeBlock struct {
	Attribute            *Attribute `protobuf:"bytes,1,opt,name=attribute,proto3" json:"attribute,omitempty"`
	Language             string     `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Lines                []*Line    `protobuf:"bytes,3,rep,name=lines,proto3" json:"lines,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CodeBlock) Reset()         { *m = CodeBlock{} }
func (m *CodeBlock) String() string { return proto.CompactTextString(m) }
func (*CodeBlock) ProtoMessage()    {}
func (*CodeBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{6}
}
func (m *CodeBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeBlock.Unmarshal(m, b)
}
func (m *CodeBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeBlock.Marshal(b, m, deterministic)
}
func (m *CodeBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeBlock.Merge(m, src)
}
func (m *CodeBlock) XXX_Size() int {
	return xxx_messageInfo_CodeBlock.Size(m)
}
func (m *CodeBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeBlock.DiscardUnknown(m)
}

var xxx_messageInfo_CodeBlock proto.InternalMessageInfo

func (m *CodeBlock) GetAttribute() *Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

func (m *CodeBlock) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *CodeBlock) GetLines() []*Line {
	if m != nil {
		return m.Lines
	}
	return nil
}

type BlockQuote struct {
	Blocks               []*Block `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockQuote) Reset()         { *m = BlockQuote{} }
func (m *BlockQuote) String() string { return proto.CompactTextString(m) }
func (*BlockQuote) ProtoMessage()    {}
func (*BlockQuote) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{7}
}
func (m *BlockQuote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockQuote.Unmarshal(m, b)
}
func (m *BlockQuote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockQuote.Marshal(b, m, deterministic)
}
func (m *BlockQuote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockQuote.Merge(m, src)
}
func (m *BlockQuote) XXX_Size() int {
	return xxx_messageInfo_BlockQuote.Size(m)
}
func (m *BlockQuote) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockQuote.DiscardUnknown(m)
}

var xxx_messageInfo_BlockQuote proto.InternalMessageInfo

func (m *BlockQuote) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type ListAttribute struct {
	BeginNumber          int64                         `protobuf:"varint,1,opt,name=begin_number,json=beginNumber,proto3" json:"beginNumber,omitempty"`
	NumberStyle          ListAttribute_NumberStyle     `protobuf:"varint,2,opt,name=number_style,json=numberStyle,proto3,enum=mojo.document.ListAttribute_NumberStyle" json:"numberStyle,omitempty"`
	NumberDelimiter      ListAttribute_NumberDelimiter `protobuf:"varint,3,opt,name=number_delimiter,json=numberDelimiter,proto3,enum=mojo.document.ListAttribute_NumberDelimiter" json:"numberDelimiter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ListAttribute) Reset()         { *m = ListAttribute{} }
func (m *ListAttribute) String() string { return proto.CompactTextString(m) }
func (*ListAttribute) ProtoMessage()    {}
func (*ListAttribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{8}
}
func (m *ListAttribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAttribute.Unmarshal(m, b)
}
func (m *ListAttribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAttribute.Marshal(b, m, deterministic)
}
func (m *ListAttribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAttribute.Merge(m, src)
}
func (m *ListAttribute) XXX_Size() int {
	return xxx_messageInfo_ListAttribute.Size(m)
}
func (m *ListAttribute) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAttribute.DiscardUnknown(m)
}

var xxx_messageInfo_ListAttribute proto.InternalMessageInfo

func (m *ListAttribute) GetBeginNumber() int64 {
	if m != nil {
		return m.BeginNumber
	}
	return 0
}

func (m *ListAttribute) GetNumberStyle() ListAttribute_NumberStyle {
	if m != nil {
		return m.NumberStyle
	}
	return ListAttribute_NUMBER_STYLE_UNSPECIFIED
}

func (m *ListAttribute) GetNumberDelimiter() ListAttribute_NumberDelimiter {
	if m != nil {
		return m.NumberDelimiter
	}
	return ListAttribute_NUMBER_DELIMITER_UNSPECIFIED
}

type OrderedList struct {
	Attribute            *ListAttribute        `protobuf:"bytes,1,opt,name=attribute,proto3" json:"attribute,omitempty"`
	Items                []*OrderedList_Blocks `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *OrderedList) Reset()         { *m = OrderedList{} }
func (m *OrderedList) String() string { return proto.CompactTextString(m) }
func (*OrderedList) ProtoMessage()    {}
func (*OrderedList) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{9}
}
func (m *OrderedList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderedList.Unmarshal(m, b)
}
func (m *OrderedList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderedList.Marshal(b, m, deterministic)
}
func (m *OrderedList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderedList.Merge(m, src)
}
func (m *OrderedList) XXX_Size() int {
	return xxx_messageInfo_OrderedList.Size(m)
}
func (m *OrderedList) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderedList.DiscardUnknown(m)
}

var xxx_messageInfo_OrderedList proto.InternalMessageInfo

func (m *OrderedList) GetAttribute() *ListAttribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

func (m *OrderedList) GetItems() []*OrderedList_Blocks {
	if m != nil {
		return m.Items
	}
	return nil
}

type OrderedList_Blocks struct {
	Values               []*Block `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderedList_Blocks) Reset()         { *m = OrderedList_Blocks{} }
func (m *OrderedList_Blocks) String() string { return proto.CompactTextString(m) }
func (*OrderedList_Blocks) ProtoMessage()    {}
func (*OrderedList_Blocks) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{9, 0}
}
func (m *OrderedList_Blocks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderedList_Blocks.Unmarshal(m, b)
}
func (m *OrderedList_Blocks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderedList_Blocks.Marshal(b, m, deterministic)
}
func (m *OrderedList_Blocks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderedList_Blocks.Merge(m, src)
}
func (m *OrderedList_Blocks) XXX_Size() int {
	return xxx_messageInfo_OrderedList_Blocks.Size(m)
}
func (m *OrderedList_Blocks) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderedList_Blocks.DiscardUnknown(m)
}

var xxx_messageInfo_OrderedList_Blocks proto.InternalMessageInfo

func (m *OrderedList_Blocks) GetValues() []*Block {
	if m != nil {
		return m.Values
	}
	return nil
}

type BulletList struct {
	Items                []*BulletList_Blocks `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BulletList) Reset()         { *m = BulletList{} }
func (m *BulletList) String() string { return proto.CompactTextString(m) }
func (*BulletList) ProtoMessage()    {}
func (*BulletList) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{10}
}
func (m *BulletList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulletList.Unmarshal(m, b)
}
func (m *BulletList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulletList.Marshal(b, m, deterministic)
}
func (m *BulletList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulletList.Merge(m, src)
}
func (m *BulletList) XXX_Size() int {
	return xxx_messageInfo_BulletList.Size(m)
}
func (m *BulletList) XXX_DiscardUnknown() {
	xxx_messageInfo_BulletList.DiscardUnknown(m)
}

var xxx_messageInfo_BulletList proto.InternalMessageInfo

func (m *BulletList) GetItems() []*BulletList_Blocks {
	if m != nil {
		return m.Items
	}
	return nil
}

type BulletList_Blocks struct {
	Values               []*Block `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BulletList_Blocks) Reset()         { *m = BulletList_Blocks{} }
func (m *BulletList_Blocks) String() string { return proto.CompactTextString(m) }
func (*BulletList_Blocks) ProtoMessage()    {}
func (*BulletList_Blocks) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{10, 0}
}
func (m *BulletList_Blocks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulletList_Blocks.Unmarshal(m, b)
}
func (m *BulletList_Blocks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulletList_Blocks.Marshal(b, m, deterministic)
}
func (m *BulletList_Blocks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulletList_Blocks.Merge(m, src)
}
func (m *BulletList_Blocks) XXX_Size() int {
	return xxx_messageInfo_BulletList_Blocks.Size(m)
}
func (m *BulletList_Blocks) XXX_DiscardUnknown() {
	xxx_messageInfo_BulletList_Blocks.DiscardUnknown(m)
}

var xxx_messageInfo_BulletList_Blocks proto.InternalMessageInfo

func (m *BulletList_Blocks) GetValues() []*Block {
	if m != nil {
		return m.Values
	}
	return nil
}

type DefinitionList struct {
	Items                []*DefinitionList_Item `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *DefinitionList) Reset()         { *m = DefinitionList{} }
func (m *DefinitionList) String() string { return proto.CompactTextString(m) }
func (*DefinitionList) ProtoMessage()    {}
func (*DefinitionList) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{11}
}
func (m *DefinitionList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DefinitionList.Unmarshal(m, b)
}
func (m *DefinitionList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DefinitionList.Marshal(b, m, deterministic)
}
func (m *DefinitionList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefinitionList.Merge(m, src)
}
func (m *DefinitionList) XXX_Size() int {
	return xxx_messageInfo_DefinitionList.Size(m)
}
func (m *DefinitionList) XXX_DiscardUnknown() {
	xxx_messageInfo_DefinitionList.DiscardUnknown(m)
}

var xxx_messageInfo_DefinitionList proto.InternalMessageInfo

func (m *DefinitionList) GetItems() []*DefinitionList_Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type DefinitionList_Item struct {
	Term                 []*Inline `protobuf:"bytes,1,rep,name=term,proto3" json:"term,omitempty"`
	Definitions          []*Blocks `protobuf:"bytes,2,rep,name=definitions,proto3" json:"definitions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DefinitionList_Item) Reset()         { *m = DefinitionList_Item{} }
func (m *DefinitionList_Item) String() string { return proto.CompactTextString(m) }
func (*DefinitionList_Item) ProtoMessage()    {}
func (*DefinitionList_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{11, 0}
}
func (m *DefinitionList_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DefinitionList_Item.Unmarshal(m, b)
}
func (m *DefinitionList_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DefinitionList_Item.Marshal(b, m, deterministic)
}
func (m *DefinitionList_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefinitionList_Item.Merge(m, src)
}
func (m *DefinitionList_Item) XXX_Size() int {
	return xxx_messageInfo_DefinitionList_Item.Size(m)
}
func (m *DefinitionList_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_DefinitionList_Item.DiscardUnknown(m)
}

var xxx_messageInfo_DefinitionList_Item proto.InternalMessageInfo

func (m *DefinitionList_Item) GetTerm() []*Inline {
	if m != nil {
		return m.Term
	}
	return nil
}

func (m *DefinitionList_Item) GetDefinitions() []*Blocks {
	if m != nil {
		return m.Definitions
	}
	return nil
}

type Header struct {
	Attribute            *Attribute `protobuf:"bytes,1,opt,name=attribute,proto3" json:"attribute,omitempty"`
	Level                int64      `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Text                 []*Inline  `protobuf:"bytes,3,rep,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{12}
}
func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetAttribute() *Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

func (m *Header) GetLevel() int64 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *Header) GetText() []*Inline {
	if m != nil {
		return m.Text
	}
	return nil
}

type Table struct {
	Caption              []*Inline       `protobuf:"bytes,1,rep,name=caption,proto3" json:"caption,omitempty"`
	Alignment            Table_Alignment `protobuf:"varint,2,opt,name=alignment,proto3,enum=mojo.document.Table_Alignment" json:"alignment,omitempty"`
	Width                float64         `protobuf:"fixed64,3,opt,name=width,proto3" json:"width,omitempty"`
	Header               *Table_Header   `protobuf:"bytes,4,opt,name=header,proto3" json:"header,omitempty"`
	Rows                 []*Table_Row    `protobuf:"bytes,5,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Table) Reset()         { *m = Table{} }
func (m *Table) String() string { return proto.CompactTextString(m) }
func (*Table) ProtoMessage()    {}
func (*Table) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{13}
}
func (m *Table) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Table.Unmarshal(m, b)
}
func (m *Table) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Table.Marshal(b, m, deterministic)
}
func (m *Table) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Table.Merge(m, src)
}
func (m *Table) XXX_Size() int {
	return xxx_messageInfo_Table.Size(m)
}
func (m *Table) XXX_DiscardUnknown() {
	xxx_messageInfo_Table.DiscardUnknown(m)
}

var xxx_messageInfo_Table proto.InternalMessageInfo

func (m *Table) GetCaption() []*Inline {
	if m != nil {
		return m.Caption
	}
	return nil
}

func (m *Table) GetAlignment() Table_Alignment {
	if m != nil {
		return m.Alignment
	}
	return Table_ALIGNMENT_UNSPECIFIED
}

func (m *Table) GetWidth() float64 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Table) GetHeader() *Table_Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Table) GetRows() []*Table_Row {
	if m != nil {
		return m.Rows
	}
	return nil
}

type Table_Cell struct {
	Values               []*Block `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Table_Cell) Reset()         { *m = Table_Cell{} }
func (m *Table_Cell) String() string { return proto.CompactTextString(m) }
func (*Table_Cell) ProtoMessage()    {}
func (*Table_Cell) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{13, 0}
}
func (m *Table_Cell) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Table_Cell.Unmarshal(m, b)
}
func (m *Table_Cell) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Table_Cell.Marshal(b, m, deterministic)
}
func (m *Table_Cell) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Table_Cell.Merge(m, src)
}
func (m *Table_Cell) XXX_Size() int {
	return xxx_messageInfo_Table_Cell.Size(m)
}
func (m *Table_Cell) XXX_DiscardUnknown() {
	xxx_messageInfo_Table_Cell.DiscardUnknown(m)
}

var xxx_messageInfo_Table_Cell proto.InternalMessageInfo

func (m *Table_Cell) GetValues() []*Block {
	if m != nil {
		return m.Values
	}
	return nil
}

type Table_Row struct {
	Values               []*Table_Cell `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Table_Row) Reset()         { *m = Table_Row{} }
func (m *Table_Row) String() string { return proto.CompactTextString(m) }
func (*Table_Row) ProtoMessage()    {}
func (*Table_Row) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{13, 1}
}
func (m *Table_Row) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Table_Row.Unmarshal(m, b)
}
func (m *Table_Row) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Table_Row.Marshal(b, m, deterministic)
}
func (m *Table_Row) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Table_Row.Merge(m, src)
}
func (m *Table_Row) XXX_Size() int {
	return xxx_messageInfo_Table_Row.Size(m)
}
func (m *Table_Row) XXX_DiscardUnknown() {
	xxx_messageInfo_Table_Row.DiscardUnknown(m)
}

var xxx_messageInfo_Table_Row proto.InternalMessageInfo

func (m *Table_Row) GetValues() []*Table_Cell {
	if m != nil {
		return m.Values
	}
	return nil
}

type Table_Header struct {
	Values               []*Table_Cell `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Table_Header) Reset()         { *m = Table_Header{} }
func (m *Table_Header) String() string { return proto.CompactTextString(m) }
func (*Table_Header) ProtoMessage()    {}
func (*Table_Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{13, 2}
}
func (m *Table_Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Table_Header.Unmarshal(m, b)
}
func (m *Table_Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Table_Header.Marshal(b, m, deterministic)
}
func (m *Table_Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Table_Header.Merge(m, src)
}
func (m *Table_Header) XXX_Size() int {
	return xxx_messageInfo_Table_Header.Size(m)
}
func (m *Table_Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Table_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Table_Header proto.InternalMessageInfo

func (m *Table_Header) GetValues() []*Table_Cell {
	if m != nil {
		return m.Values
	}
	return nil
}

type Division struct {
	Attribute            *Attribute `protobuf:"bytes,1,opt,name=attribute,proto3" json:"attribute,omitempty"`
	Content              []*Block   `protobuf:"bytes,2,rep,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Division) Reset()         { *m = Division{} }
func (m *Division) String() string { return proto.CompactTextString(m) }
func (*Division) ProtoMessage()    {}
func (*Division) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{14}
}
func (m *Division) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Division.Unmarshal(m, b)
}
func (m *Division) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Division.Marshal(b, m, deterministic)
}
func (m *Division) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Division.Merge(m, src)
}
func (m *Division) XXX_Size() int {
	return xxx_messageInfo_Division.Size(m)
}
func (m *Division) XXX_DiscardUnknown() {
	xxx_messageInfo_Division.DiscardUnknown(m)
}

var xxx_messageInfo_Division proto.InternalMessageInfo

func (m *Division) GetAttribute() *Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

func (m *Division) GetContent() []*Block {
	if m != nil {
		return m.Content
	}
	return nil
}

type Blocks struct {
	Values               []*Block `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blocks) Reset()         { *m = Blocks{} }
func (m *Blocks) String() string { return proto.CompactTextString(m) }
func (*Blocks) ProtoMessage()    {}
func (*Blocks) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{15}
}
func (m *Blocks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blocks.Unmarshal(m, b)
}
func (m *Blocks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blocks.Marshal(b, m, deterministic)
}
func (m *Blocks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blocks.Merge(m, src)
}
func (m *Blocks) XXX_Size() int {
	return xxx_messageInfo_Blocks.Size(m)
}
func (m *Blocks) XXX_DiscardUnknown() {
	xxx_messageInfo_Blocks.DiscardUnknown(m)
}

var xxx_messageInfo_Blocks proto.InternalMessageInfo

func (m *Blocks) GetValues() []*Block {
	if m != nil {
		return m.Values
	}
	return nil
}

type Inline struct {
	// Types that are valid to be assigned to Inline:
	//	*Inline_Text
	//	*Inline_Emphasized
	//	*Inline_Strong
	//	*Inline_Strikeout
	//	*Inline_Superscript
	//	*Inline_Subscript
	//	*Inline_SmallCaps
	//	*Inline_Quoted
	//	*Inline_Cite
	//	*Inline_Code
	//	*Inline_Space
	//	*Inline_LineBreak
	//	*Inline_Link
	//	*Inline_Image
	//	*Inline_Note
	//	*Inline_Span
	Inline               isInline_Inline `protobuf_oneof:"inline"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Inline) Reset()         { *m = Inline{} }
func (m *Inline) String() string { return proto.CompactTextString(m) }
func (*Inline) ProtoMessage()    {}
func (*Inline) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{16}
}
func (m *Inline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Inline.Unmarshal(m, b)
}
func (m *Inline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Inline.Marshal(b, m, deterministic)
}
func (m *Inline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Inline.Merge(m, src)
}
func (m *Inline) XXX_Size() int {
	return xxx_messageInfo_Inline.Size(m)
}
func (m *Inline) XXX_DiscardUnknown() {
	xxx_messageInfo_Inline.DiscardUnknown(m)
}

var xxx_messageInfo_Inline proto.InternalMessageInfo

type isInline_Inline interface {
	isInline_Inline()
}

type Inline_Text struct {
	Text *Text `protobuf:"bytes,1,opt,name=text,proto3,oneof" json:"text,omitempty"`
}
type Inline_Emphasized struct {
	Emphasized *Emphasized `protobuf:"bytes,2,opt,name=emphasized,proto3,oneof" json:"emphasized,omitempty"`
}
type Inline_Strong struct {
	Strong *Strong `protobuf:"bytes,3,opt,name=strong,proto3,oneof" json:"strong,omitempty"`
}
type Inline_Strikeout struct {
	Strikeout *Strikeout `protobuf:"bytes,4,opt,name=strikeout,proto3,oneof" json:"strikeout,omitempty"`
}
type Inline_Superscript struct {
	Superscript *Superscript `protobuf:"bytes,5,opt,name=superscript,proto3,oneof" json:"superscript,omitempty"`
}
type Inline_Subscript struct {
	Subscript *Subscript `protobuf:"bytes,6,opt,name=subscript,proto3,oneof" json:"subscript,omitempty"`
}
type Inline_SmallCaps struct {
	SmallCaps *SmallCaps `protobuf:"bytes,7,opt,name=small_caps,json=smallCaps,proto3,oneof" json:"smallCaps,omitempty"`
}
type Inline_Quoted struct {
	Quoted *Quoted `protobuf:"bytes,8,opt,name=quoted,proto3,oneof" json:"quoted,omitempty"`
}
type Inline_Cite struct {
	Cite *Cite `protobuf:"bytes,9,opt,name=cite,proto3,oneof" json:"cite,omitempty"`
}
type Inline_Code struct {
	Code *Code `protobuf:"bytes,10,opt,name=code,proto3,oneof" json:"code,omitempty"`
}
type Inline_Space struct {
	Space *Space `protobuf:"bytes,11,opt,name=space,proto3,oneof" json:"space,omitempty"`
}
type Inline_LineBreak struct {
	LineBreak *LineBreak `protobuf:"bytes,12,opt,name=line_break,json=lineBreak,proto3,oneof" json:"lineBreak,omitempty"`
}
type Inline_Link struct {
	Link *Link `protobuf:"bytes,13,opt,name=link,proto3,oneof" json:"link,omitempty"`
}
type Inline_Image struct {
	Image *Image `protobuf:"bytes,14,opt,name=image,proto3,oneof" json:"image,omitempty"`
}
type Inline_Note struct {
	Note *Note `protobuf:"bytes,15,opt,name=note,proto3,oneof" json:"note,omitempty"`
}
type Inline_Span struct {
	Span *Span `protobuf:"bytes,16,opt,name=span,proto3,oneof" json:"span,omitempty"`
}

func (*Inline_Text) isInline_Inline()        {}
func (*Inline_Emphasized) isInline_Inline()  {}
func (*Inline_Strong) isInline_Inline()      {}
func (*Inline_Strikeout) isInline_Inline()   {}
func (*Inline_Superscript) isInline_Inline() {}
func (*Inline_Subscript) isInline_Inline()   {}
func (*Inline_SmallCaps) isInline_Inline()   {}
func (*Inline_Quoted) isInline_Inline()      {}
func (*Inline_Cite) isInline_Inline()        {}
func (*Inline_Code) isInline_Inline()        {}
func (*Inline_Space) isInline_Inline()       {}
func (*Inline_LineBreak) isInline_Inline()   {}
func (*Inline_Link) isInline_Inline()        {}
func (*Inline_Image) isInline_Inline()       {}
func (*Inline_Note) isInline_Inline()        {}
func (*Inline_Span) isInline_Inline()        {}

func (m *Inline) GetInline() isInline_Inline {
	if m != nil {
		return m.Inline
	}
	return nil
}

func (m *Inline) GetText() *Text {
	if x, ok := m.GetInline().(*Inline_Text); ok {
		return x.Text
	}
	return nil
}

func (m *Inline) GetEmphasized() *Emphasized {
	if x, ok := m.GetInline().(*Inline_Emphasized); ok {
		return x.Emphasized
	}
	return nil
}

func (m *Inline) GetStrong() *Strong {
	if x, ok := m.GetInline().(*Inline_Strong); ok {
		return x.Strong
	}
	return nil
}

func (m *Inline) GetStrikeout() *Strikeout {
	if x, ok := m.GetInline().(*Inline_Strikeout); ok {
		return x.Strikeout
	}
	return nil
}

func (m *Inline) GetSuperscript() *Superscript {
	if x, ok := m.GetInline().(*Inline_Superscript); ok {
		return x.Superscript
	}
	return nil
}

func (m *Inline) GetSubscript() *Subscript {
	if x, ok := m.GetInline().(*Inline_Subscript); ok {
		return x.Subscript
	}
	return nil
}

func (m *Inline) GetSmallCaps() *SmallCaps {
	if x, ok := m.GetInline().(*Inline_SmallCaps); ok {
		return x.SmallCaps
	}
	return nil
}

func (m *Inline) GetQuoted() *Quoted {
	if x, ok := m.GetInline().(*Inline_Quoted); ok {
		return x.Quoted
	}
	return nil
}

func (m *Inline) GetCite() *Cite {
	if x, ok := m.GetInline().(*Inline_Cite); ok {
		return x.Cite
	}
	return nil
}

func (m *Inline) GetCode() *Code {
	if x, ok := m.GetInline().(*Inline_Code); ok {
		return x.Code
	}
	return nil
}

func (m *Inline) GetSpace() *Space {
	if x, ok := m.GetInline().(*Inline_Space); ok {
		return x.Space
	}
	return nil
}

func (m *Inline) GetLineBreak() *LineBreak {
	if x, ok := m.GetInline().(*Inline_LineBreak); ok {
		return x.LineBreak
	}
	return nil
}

func (m *Inline) GetLink() *Link {
	if x, ok := m.GetInline().(*Inline_Link); ok {
		return x.Link
	}
	return nil
}

func (m *Inline) GetImage() *Image {
	if x, ok := m.GetInline().(*Inline_Image); ok {
		return x.Image
	}
	return nil
}

func (m *Inline) GetNote() *Note {
	if x, ok := m.GetInline().(*Inline_Note); ok {
		return x.Note
	}
	return nil
}

func (m *Inline) GetSpan() *Span {
	if x, ok := m.GetInline().(*Inline_Span); ok {
		return x.Span
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Inline) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Inline_Text)(nil),
		(*Inline_Emphasized)(nil),
		(*Inline_Strong)(nil),
		(*Inline_Strikeout)(nil),
		(*Inline_Superscript)(nil),
		(*Inline_Subscript)(nil),
		(*Inline_SmallCaps)(nil),
		(*Inline_Quoted)(nil),
		(*Inline_Cite)(nil),
		(*Inline_Code)(nil),
		(*Inline_Space)(nil),
		(*Inline_LineBreak)(nil),
		(*Inline_Link)(nil),
		(*Inline_Image)(nil),
		(*Inline_Note)(nil),
		(*Inline_Span)(nil),
	}
}

type Text struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Text) Reset()         { *m = Text{} }
func (m *Text) String() string { return proto.CompactTextString(m) }
func (*Text) ProtoMessage()    {}
func (*Text) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{17}
}
func (m *Text) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Text.Unmarshal(m, b)
}
func (m *Text) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Text.Marshal(b, m, deterministic)
}
func (m *Text) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Text.Merge(m, src)
}
func (m *Text) XXX_Size() int {
	return xxx_messageInfo_Text.Size(m)
}
func (m *Text) XXX_DiscardUnknown() {
	xxx_messageInfo_Text.DiscardUnknown(m)
}

var xxx_messageInfo_Text proto.InternalMessageInfo

func (m *Text) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Emphasized struct {
	Values               []*Inline `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Emphasized) Reset()         { *m = Emphasized{} }
func (m *Emphasized) String() string { return proto.CompactTextString(m) }
func (*Emphasized) ProtoMessage()    {}
func (*Emphasized) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{18}
}
func (m *Emphasized) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Emphasized.Unmarshal(m, b)
}
func (m *Emphasized) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Emphasized.Marshal(b, m, deterministic)
}
func (m *Emphasized) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Emphasized.Merge(m, src)
}
func (m *Emphasized) XXX_Size() int {
	return xxx_messageInfo_Emphasized.Size(m)
}
func (m *Emphasized) XXX_DiscardUnknown() {
	xxx_messageInfo_Emphasized.DiscardUnknown(m)
}

var xxx_messageInfo_Emphasized proto.InternalMessageInfo

func (m *Emphasized) GetValues() []*Inline {
	if m != nil {
		return m.Values
	}
	return nil
}

type Strong struct {
	Values               []*Inline `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Strong) Reset()         { *m = Strong{} }
func (m *Strong) String() string { return proto.CompactTextString(m) }
func (*Strong) ProtoMessage()    {}
func (*Strong) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{19}
}
func (m *Strong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Strong.Unmarshal(m, b)
}
func (m *Strong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Strong.Marshal(b, m, deterministic)
}
func (m *Strong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Strong.Merge(m, src)
}
func (m *Strong) XXX_Size() int {
	return xxx_messageInfo_Strong.Size(m)
}
func (m *Strong) XXX_DiscardUnknown() {
	xxx_messageInfo_Strong.DiscardUnknown(m)
}

var xxx_messageInfo_Strong proto.InternalMessageInfo

func (m *Strong) GetValues() []*Inline {
	if m != nil {
		return m.Values
	}
	return nil
}

type Strikeout struct {
	Values               []*Inline `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Strikeout) Reset()         { *m = Strikeout{} }
func (m *Strikeout) String() string { return proto.CompactTextString(m) }
func (*Strikeout) ProtoMessage()    {}
func (*Strikeout) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{20}
}
func (m *Strikeout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Strikeout.Unmarshal(m, b)
}
func (m *Strikeout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Strikeout.Marshal(b, m, deterministic)
}
func (m *Strikeout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Strikeout.Merge(m, src)
}
func (m *Strikeout) XXX_Size() int {
	return xxx_messageInfo_Strikeout.Size(m)
}
func (m *Strikeout) XXX_DiscardUnknown() {
	xxx_messageInfo_Strikeout.DiscardUnknown(m)
}

var xxx_messageInfo_Strikeout proto.InternalMessageInfo

func (m *Strikeout) GetValues() []*Inline {
	if m != nil {
		return m.Values
	}
	return nil
}

type Superscript struct {
	Values               []*Inline `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Superscript) Reset()         { *m = Superscript{} }
func (m *Superscript) String() string { return proto.CompactTextString(m) }
func (*Superscript) ProtoMessage()    {}
func (*Superscript) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{21}
}
func (m *Superscript) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Superscript.Unmarshal(m, b)
}
func (m *Superscript) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Superscript.Marshal(b, m, deterministic)
}
func (m *Superscript) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Superscript.Merge(m, src)
}
func (m *Superscript) XXX_Size() int {
	return xxx_messageInfo_Superscript.Size(m)
}
func (m *Superscript) XXX_DiscardUnknown() {
	xxx_messageInfo_Superscript.DiscardUnknown(m)
}

var xxx_messageInfo_Superscript proto.InternalMessageInfo

func (m *Superscript) GetValues() []*Inline {
	if m != nil {
		return m.Values
	}
	return nil
}

type Subscript struct {
	Values               []*Inline `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Subscript) Reset()         { *m = Subscript{} }
func (m *Subscript) String() string { return proto.CompactTextString(m) }
func (*Subscript) ProtoMessage()    {}
func (*Subscript) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{22}
}
func (m *Subscript) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subscript.Unmarshal(m, b)
}
func (m *Subscript) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subscript.Marshal(b, m, deterministic)
}
func (m *Subscript) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subscript.Merge(m, src)
}
func (m *Subscript) XXX_Size() int {
	return xxx_messageInfo_Subscript.Size(m)
}
func (m *Subscript) XXX_DiscardUnknown() {
	xxx_messageInfo_Subscript.DiscardUnknown(m)
}

var xxx_messageInfo_Subscript proto.InternalMessageInfo

func (m *Subscript) GetValues() []*Inline {
	if m != nil {
		return m.Values
	}
	return nil
}

type SmallCaps struct {
	Values               []*Inline `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SmallCaps) Reset()         { *m = SmallCaps{} }
func (m *SmallCaps) String() string { return proto.CompactTextString(m) }
func (*SmallCaps) ProtoMessage()    {}
func (*SmallCaps) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{23}
}
func (m *SmallCaps) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmallCaps.Unmarshal(m, b)
}
func (m *SmallCaps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmallCaps.Marshal(b, m, deterministic)
}
func (m *SmallCaps) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmallCaps.Merge(m, src)
}
func (m *SmallCaps) XXX_Size() int {
	return xxx_messageInfo_SmallCaps.Size(m)
}
func (m *SmallCaps) XXX_DiscardUnknown() {
	xxx_messageInfo_SmallCaps.DiscardUnknown(m)
}

var xxx_messageInfo_SmallCaps proto.InternalMessageInfo

func (m *SmallCaps) GetValues() []*Inline {
	if m != nil {
		return m.Values
	}
	return nil
}

type Space struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Space) Reset()         { *m = Space{} }
func (m *Space) String() string { return proto.CompactTextString(m) }
func (*Space) ProtoMessage()    {}
func (*Space) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{24}
}
func (m *Space) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Space.Unmarshal(m, b)
}
func (m *Space) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Space.Marshal(b, m, deterministic)
}
func (m *Space) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Space.Merge(m, src)
}
func (m *Space) XXX_Size() int {
	return xxx_messageInfo_Space.Size(m)
}
func (m *Space) XXX_DiscardUnknown() {
	xxx_messageInfo_Space.DiscardUnknown(m)
}

var xxx_messageInfo_Space proto.InternalMessageInfo

type LineBreak struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LineBreak) Reset()         { *m = LineBreak{} }
func (m *LineBreak) String() string { return proto.CompactTextString(m) }
func (*LineBreak) ProtoMessage()    {}
func (*LineBreak) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{25}
}
func (m *LineBreak) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LineBreak.Unmarshal(m, b)
}
func (m *LineBreak) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LineBreak.Marshal(b, m, deterministic)
}
func (m *LineBreak) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LineBreak.Merge(m, src)
}
func (m *LineBreak) XXX_Size() int {
	return xxx_messageInfo_LineBreak.Size(m)
}
func (m *LineBreak) XXX_DiscardUnknown() {
	xxx_messageInfo_LineBreak.DiscardUnknown(m)
}

var xxx_messageInfo_LineBreak proto.InternalMessageInfo

type Note struct {
	Values               []*Block `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Note) Reset()         { *m = Note{} }
func (m *Note) String() string { return proto.CompactTextString(m) }
func (*Note) ProtoMessage()    {}
func (*Note) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{26}
}
func (m *Note) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Note.Unmarshal(m, b)
}
func (m *Note) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Note.Marshal(b, m, deterministic)
}
func (m *Note) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Note.Merge(m, src)
}
func (m *Note) XXX_Size() int {
	return xxx_messageInfo_Note.Size(m)
}
func (m *Note) XXX_DiscardUnknown() {
	xxx_messageInfo_Note.DiscardUnknown(m)
}

var xxx_messageInfo_Note proto.InternalMessageInfo

func (m *Note) GetValues() []*Block {
	if m != nil {
		return m.Values
	}
	return nil
}

type Quoted struct {
	Type                 Quoted_Type `protobuf:"varint,1,opt,name=type,proto3,enum=mojo.document.Quoted_Type" json:"type,omitempty"`
	Text                 []*Inline   `protobuf:"bytes,2,rep,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Quoted) Reset()         { *m = Quoted{} }
func (m *Quoted) String() string { return proto.CompactTextString(m) }
func (*Quoted) ProtoMessage()    {}
func (*Quoted) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{27}
}
func (m *Quoted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Quoted.Unmarshal(m, b)
}
func (m *Quoted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Quoted.Marshal(b, m, deterministic)
}
func (m *Quoted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Quoted.Merge(m, src)
}
func (m *Quoted) XXX_Size() int {
	return xxx_messageInfo_Quoted.Size(m)
}
func (m *Quoted) XXX_DiscardUnknown() {
	xxx_messageInfo_Quoted.DiscardUnknown(m)
}

var xxx_messageInfo_Quoted proto.InternalMessageInfo

func (m *Quoted) GetType() Quoted_Type {
	if m != nil {
		return m.Type
	}
	return Quoted_TYPE_DOUBLE
}

func (m *Quoted) GetText() []*Inline {
	if m != nil {
		return m.Text
	}
	return nil
}

type Cite struct {
	Citations            []*Citation `protobuf:"bytes,1,rep,name=citations,proto3" json:"citations,omitempty"`
	Inlines              []*Inline   `protobuf:"bytes,2,rep,name=inlines,proto3" json:"inlines,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Cite) Reset()         { *m = Cite{} }
func (m *Cite) String() string { return proto.CompactTextString(m) }
func (*Cite) ProtoMessage()    {}
func (*Cite) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{28}
}
func (m *Cite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cite.Unmarshal(m, b)
}
func (m *Cite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cite.Marshal(b, m, deterministic)
}
func (m *Cite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cite.Merge(m, src)
}
func (m *Cite) XXX_Size() int {
	return xxx_messageInfo_Cite.Size(m)
}
func (m *Cite) XXX_DiscardUnknown() {
	xxx_messageInfo_Cite.DiscardUnknown(m)
}

var xxx_messageInfo_Cite proto.InternalMessageInfo

func (m *Cite) GetCitations() []*Citation {
	if m != nil {
		return m.Citations
	}
	return nil
}

func (m *Cite) GetInlines() []*Inline {
	if m != nil {
		return m.Inlines
	}
	return nil
}

type Citation struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Prefix               []*Inline     `protobuf:"bytes,2,rep,name=prefix,proto3" json:"prefix,omitempty"`
	Suffix               []*Inline     `protobuf:"bytes,3,rep,name=suffix,proto3" json:"suffix,omitempty"`
	Mode                 Citation_Mode `protobuf:"varint,4,opt,name=mode,proto3,enum=mojo.document.Citation_Mode" json:"mode,omitempty"`
	NoteCount            int64         `protobuf:"varint,5,opt,name=note_count,json=noteCount,proto3" json:"noteCount,omitempty"`
	Hash                 int64         `protobuf:"varint,6,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Citation) Reset()         { *m = Citation{} }
func (m *Citation) String() string { return proto.CompactTextString(m) }
func (*Citation) ProtoMessage()    {}
func (*Citation) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{29}
}
func (m *Citation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Citation.Unmarshal(m, b)
}
func (m *Citation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Citation.Marshal(b, m, deterministic)
}
func (m *Citation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Citation.Merge(m, src)
}
func (m *Citation) XXX_Size() int {
	return xxx_messageInfo_Citation.Size(m)
}
func (m *Citation) XXX_DiscardUnknown() {
	xxx_messageInfo_Citation.DiscardUnknown(m)
}

var xxx_messageInfo_Citation proto.InternalMessageInfo

func (m *Citation) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Citation) GetPrefix() []*Inline {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *Citation) GetSuffix() []*Inline {
	if m != nil {
		return m.Suffix
	}
	return nil
}

func (m *Citation) GetMode() Citation_Mode {
	if m != nil {
		return m.Mode
	}
	return Citation_MODE_NORMAL
}

func (m *Citation) GetNoteCount() int64 {
	if m != nil {
		return m.NoteCount
	}
	return 0
}

func (m *Citation) GetHash() int64 {
	if m != nil {
		return m.Hash
	}
	return 0
}

type Code struct {
	Attribute            *Attribute `protobuf:"bytes,1,opt,name=attribute,proto3" json:"attribute,omitempty"`
	Content              string     `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Code) Reset()         { *m = Code{} }
func (m *Code) String() string { return proto.CompactTextString(m) }
func (*Code) ProtoMessage()    {}
func (*Code) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{30}
}
func (m *Code) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Code.Unmarshal(m, b)
}
func (m *Code) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Code.Marshal(b, m, deterministic)
}
func (m *Code) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Code.Merge(m, src)
}
func (m *Code) XXX_Size() int {
	return xxx_messageInfo_Code.Size(m)
}
func (m *Code) XXX_DiscardUnknown() {
	xxx_messageInfo_Code.DiscardUnknown(m)
}

var xxx_messageInfo_Code proto.InternalMessageInfo

func (m *Code) GetAttribute() *Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

func (m *Code) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type Link struct {
	Attribute            *Attribute `protobuf:"bytes,1,opt,name=attribute,proto3" json:"attribute,omitempty"`
	Description          []*Inline  `protobuf:"bytes,2,rep,name=description,proto3" json:"description,omitempty"`
	Target               *Target    `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Link) Reset()         { *m = Link{} }
func (m *Link) String() string { return proto.CompactTextString(m) }
func (*Link) ProtoMessage()    {}
func (*Link) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{31}
}
func (m *Link) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Link.Unmarshal(m, b)
}
func (m *Link) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Link.Marshal(b, m, deterministic)
}
func (m *Link) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Link.Merge(m, src)
}
func (m *Link) XXX_Size() int {
	return xxx_messageInfo_Link.Size(m)
}
func (m *Link) XXX_DiscardUnknown() {
	xxx_messageInfo_Link.DiscardUnknown(m)
}

var xxx_messageInfo_Link proto.InternalMessageInfo

func (m *Link) GetAttribute() *Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

func (m *Link) GetDescription() []*Inline {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *Link) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

type Image struct {
	Attribute            *Attribute `protobuf:"bytes,1,opt,name=attribute,proto3" json:"attribute,omitempty"`
	Description          []*Inline  `protobuf:"bytes,2,rep,name=description,proto3" json:"description,omitempty"`
	Target               *Target    `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{32}
}
func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetAttribute() *Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

func (m *Image) GetDescription() []*Inline {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *Image) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

type Span struct {
	Attribute            *Attribute `protobuf:"bytes,1,opt,name=attribute,proto3" json:"attribute,omitempty"`
	Inlines              []*Inline  `protobuf:"bytes,2,rep,name=inlines,proto3" json:"inlines,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Span) Reset()         { *m = Span{} }
func (m *Span) String() string { return proto.CompactTextString(m) }
func (*Span) ProtoMessage()    {}
func (*Span) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{33}
}
func (m *Span) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Span.Unmarshal(m, b)
}
func (m *Span) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Span.Marshal(b, m, deterministic)
}
func (m *Span) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Span.Merge(m, src)
}
func (m *Span) XXX_Size() int {
	return xxx_messageInfo_Span.Size(m)
}
func (m *Span) XXX_DiscardUnknown() {
	xxx_messageInfo_Span.DiscardUnknown(m)
}

var xxx_messageInfo_Span proto.InternalMessageInfo

func (m *Span) GetAttribute() *Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

func (m *Span) GetInlines() []*Inline {
	if m != nil {
		return m.Inlines
	}
	return nil
}

type Target struct {
	Title                string    `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Url                  *core.Url `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Target) Reset()         { *m = Target{} }
func (m *Target) String() string { return proto.CompactTextString(m) }
func (*Target) ProtoMessage()    {}
func (*Target) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{34}
}
func (m *Target) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Target.Unmarshal(m, b)
}
func (m *Target) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Target.Marshal(b, m, deterministic)
}
func (m *Target) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Target.Merge(m, src)
}
func (m *Target) XXX_Size() int {
	return xxx_messageInfo_Target.Size(m)
}
func (m *Target) XXX_DiscardUnknown() {
	xxx_messageInfo_Target.DiscardUnknown(m)
}

var xxx_messageInfo_Target proto.InternalMessageInfo

func (m *Target) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Target) GetUrl() *core.Url {
	if m != nil {
		return m.Url
	}
	return nil
}

type Inlines struct {
	Values               []*Inline `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Inlines) Reset()         { *m = Inlines{} }
func (m *Inlines) String() string { return proto.CompactTextString(m) }
func (*Inlines) ProtoMessage()    {}
func (*Inlines) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{35}
}
func (m *Inlines) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Inlines.Unmarshal(m, b)
}
func (m *Inlines) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Inlines.Marshal(b, m, deterministic)
}
func (m *Inlines) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Inlines.Merge(m, src)
}
func (m *Inlines) XXX_Size() int {
	return xxx_messageInfo_Inlines.Size(m)
}
func (m *Inlines) XXX_DiscardUnknown() {
	xxx_messageInfo_Inlines.DiscardUnknown(m)
}

var xxx_messageInfo_Inlines proto.InternalMessageInfo

func (m *Inlines) GetValues() []*Inline {
	if m != nil {
		return m.Values
	}
	return nil
}

type MetaData struct {
	Values               map[string]*MetaValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *MetaData) Reset()         { *m = MetaData{} }
func (m *MetaData) String() string { return proto.CompactTextString(m) }
func (*MetaData) ProtoMessage()    {}
func (*MetaData) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{36}
}
func (m *MetaData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaData.Unmarshal(m, b)
}
func (m *MetaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaData.Marshal(b, m, deterministic)
}
func (m *MetaData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaData.Merge(m, src)
}
func (m *MetaData) XXX_Size() int {
	return xxx_messageInfo_MetaData.Size(m)
}
func (m *MetaData) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaData.DiscardUnknown(m)
}

var xxx_messageInfo_MetaData proto.InternalMessageInfo

func (m *MetaData) GetValues() map[string]*MetaValue {
	if m != nil {
		return m.Values
	}
	return nil
}

type MetaValueObject struct {
	Values               map[string]*MetaValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *MetaValueObject) Reset()         { *m = MetaValueObject{} }
func (m *MetaValueObject) String() string { return proto.CompactTextString(m) }
func (*MetaValueObject) ProtoMessage()    {}
func (*MetaValueObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{37}
}
func (m *MetaValueObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaValueObject.Unmarshal(m, b)
}
func (m *MetaValueObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaValueObject.Marshal(b, m, deterministic)
}
func (m *MetaValueObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaValueObject.Merge(m, src)
}
func (m *MetaValueObject) XXX_Size() int {
	return xxx_messageInfo_MetaValueObject.Size(m)
}
func (m *MetaValueObject) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaValueObject.DiscardUnknown(m)
}

var xxx_messageInfo_MetaValueObject proto.InternalMessageInfo

func (m *MetaValueObject) GetValues() map[string]*MetaValue {
	if m != nil {
		return m.Values
	}
	return nil
}

type MetaValues struct {
	Values               []*MetaValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MetaValues) Reset()         { *m = MetaValues{} }
func (m *MetaValues) String() string { return proto.CompactTextString(m) }
func (*MetaValues) ProtoMessage()    {}
func (*MetaValues) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{38}
}
func (m *MetaValues) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaValues.Unmarshal(m, b)
}
func (m *MetaValues) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaValues.Marshal(b, m, deterministic)
}
func (m *MetaValues) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaValues.Merge(m, src)
}
func (m *MetaValues) XXX_Size() int {
	return xxx_messageInfo_MetaValues.Size(m)
}
func (m *MetaValues) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaValues.DiscardUnknown(m)
}

var xxx_messageInfo_MetaValues proto.InternalMessageInfo

func (m *MetaValues) GetValues() []*MetaValue {
	if m != nil {
		return m.Values
	}
	return nil
}

type MetaValue struct {
	// Types that are valid to be assigned to MetaValue:
	//	*MetaValue_MetaValueObjectVal
	//	*MetaValue_MetaValuesVal
	//	*MetaValue_BoolVal
	//	*MetaValue_StringVal
	//	*MetaValue_DateTimeVal
	//	*MetaValue_InlinesVal
	//	*MetaValue_BlocksVal
	MetaValue            isMetaValue_MetaValue `protobuf_oneof:"meta_value"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *MetaValue) Reset()         { *m = MetaValue{} }
func (m *MetaValue) String() string { return proto.CompactTextString(m) }
func (*MetaValue) ProtoMessage()    {}
func (*MetaValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_6211100ee17574eb, []int{39}
}
func (m *MetaValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaValue.Unmarshal(m, b)
}
func (m *MetaValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaValue.Marshal(b, m, deterministic)
}
func (m *MetaValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaValue.Merge(m, src)
}
func (m *MetaValue) XXX_Size() int {
	return xxx_messageInfo_MetaValue.Size(m)
}
func (m *MetaValue) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaValue.DiscardUnknown(m)
}

var xxx_messageInfo_MetaValue proto.InternalMessageInfo

type isMetaValue_MetaValue interface {
	isMetaValue_MetaValue()
}

type MetaValue_MetaValueObjectVal struct {
	MetaValueObjectVal *MetaValueObject `protobuf:"bytes,1,opt,name=meta_value_object_val,json=metaValueObjectVal,proto3,oneof" json:"metaValueObjectVal,omitempty"`
}
type MetaValue_MetaValuesVal struct {
	MetaValuesVal *MetaValues `protobuf:"bytes,2,opt,name=meta_values_val,json=metaValuesVal,proto3,oneof" json:"metaValuesVal,omitempty"`
}
type MetaValue_BoolVal struct {
	BoolVal bool `protobuf:"varint,3,opt,name=bool_val,json=boolVal,proto3,oneof" json:"boolVal,omitempty"`
}
type MetaValue_StringVal struct {
	StringVal string `protobuf:"bytes,4,opt,name=string_val,json=stringVal,proto3,oneof" json:"stringVal,omitempty"`
}
type MetaValue_DateTimeVal struct {
	DateTimeVal *core.DateTime `protobuf:"bytes,10,opt,name=date_time_val,json=dateTimeVal,proto3,oneof" json:"dateTimeVal,omitempty"`
}
type MetaValue_InlinesVal struct {
	InlinesVal *Inlines `protobuf:"bytes,14,opt,name=inlines_val,json=inlinesVal,proto3,oneof" json:"inlinesVal,omitempty"`
}
type MetaValue_BlocksVal struct {
	BlocksVal *Blocks `protobuf:"bytes,15,opt,name=blocks_val,json=blocksVal,proto3,oneof" json:"blocksVal,omitempty"`
}

func (*MetaValue_MetaValueObjectVal) isMetaValue_MetaValue() {}
func (*MetaValue_MetaValuesVal) isMetaValue_MetaValue()      {}
func (*MetaValue_BoolVal) isMetaValue_MetaValue()            {}
func (*MetaValue_StringVal) isMetaValue_MetaValue()          {}
func (*MetaValue_DateTimeVal) isMetaValue_MetaValue()        {}
func (*MetaValue_InlinesVal) isMetaValue_MetaValue()         {}
func (*MetaValue_BlocksVal) isMetaValue_MetaValue()          {}

func (m *MetaValue) GetMetaValue() isMetaValue_MetaValue {
	if m != nil {
		return m.MetaValue
	}
	return nil
}

func (m *MetaValue) GetMetaValueObjectVal() *MetaValueObject {
	if x, ok := m.GetMetaValue().(*MetaValue_MetaValueObjectVal); ok {
		return x.MetaValueObjectVal
	}
	return nil
}

func (m *MetaValue) GetMetaValuesVal() *MetaValues {
	if x, ok := m.GetMetaValue().(*MetaValue_MetaValuesVal); ok {
		return x.MetaValuesVal
	}
	return nil
}

func (m *MetaValue) GetBoolVal() bool {
	if x, ok := m.GetMetaValue().(*MetaValue_BoolVal); ok {
		return x.BoolVal
	}
	return false
}

func (m *MetaValue) GetStringVal() string {
	if x, ok := m.GetMetaValue().(*MetaValue_StringVal); ok {
		return x.StringVal
	}
	return ""
}

func (m *MetaValue) GetDateTimeVal() *core.DateTime {
	if x, ok := m.GetMetaValue().(*MetaValue_DateTimeVal); ok {
		return x.DateTimeVal
	}
	return nil
}

func (m *MetaValue) GetInlinesVal() *Inlines {
	if x, ok := m.GetMetaValue().(*MetaValue_InlinesVal); ok {
		return x.InlinesVal
	}
	return nil
}

func (m *MetaValue) GetBlocksVal() *Blocks {
	if x, ok := m.GetMetaValue().(*MetaValue_BlocksVal); ok {
		return x.BlocksVal
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MetaValue) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MetaValue_MetaValueObjectVal)(nil),
		(*MetaValue_MetaValuesVal)(nil),
		(*MetaValue_BoolVal)(nil),
		(*MetaValue_StringVal)(nil),
		(*MetaValue_DateTimeVal)(nil),
		(*MetaValue_InlinesVal)(nil),
		(*MetaValue_BlocksVal)(nil),
	}
}

func init() {
	proto.RegisterEnum("mojo.document.ListAttribute_NumberStyle", ListAttribute_NumberStyle_name, ListAttribute_NumberStyle_value)
	proto.RegisterEnum("mojo.document.ListAttribute_NumberDelimiter", ListAttribute_NumberDelimiter_name, ListAttribute_NumberDelimiter_value)
	proto.RegisterEnum("mojo.document.Table_Alignment", Table_Alignment_name, Table_Alignment_value)
	proto.RegisterEnum("mojo.document.Quoted_Type", Quoted_Type_name, Quoted_Type_value)
	proto.RegisterEnum("mojo.document.Citation_Mode", Citation_Mode_name, Citation_Mode_value)
	proto.RegisterType((*Document)(nil), "mojo.document.Document")
	proto.RegisterType((*Block)(nil), "mojo.document.Block")
	proto.RegisterType((*Line)(nil), "mojo.document.Line")
	proto.RegisterType((*Plain)(nil), "mojo.document.Plain")
	proto.RegisterType((*Paragraph)(nil), "mojo.document.Paragraph")
	proto.RegisterType((*LineBlock)(nil), "mojo.document.LineBlock")
	proto.RegisterType((*CodeBlock)(nil), "mojo.document.CodeBlock")
	proto.RegisterType((*BlockQuote)(nil), "mojo.document.BlockQuote")
	proto.RegisterType((*ListAttribute)(nil), "mojo.document.ListAttribute")
	proto.RegisterType((*OrderedList)(nil), "mojo.document.OrderedList")
	proto.RegisterType((*OrderedList_Blocks)(nil), "mojo.document.OrderedList.Blocks")
	proto.RegisterType((*BulletList)(nil), "mojo.document.BulletList")
	proto.RegisterType((*BulletList_Blocks)(nil), "mojo.document.BulletList.Blocks")
	proto.RegisterType((*DefinitionList)(nil), "mojo.document.DefinitionList")
	proto.RegisterType((*DefinitionList_Item)(nil), "mojo.document.DefinitionList.Item")
	proto.RegisterType((*Header)(nil), "mojo.document.Header")
	proto.RegisterType((*Table)(nil), "mojo.document.Table")
	proto.RegisterType((*Table_Cell)(nil), "mojo.document.Table.Cell")
	proto.RegisterType((*Table_Row)(nil), "mojo.document.Table.Row")
	proto.RegisterType((*Table_Header)(nil), "mojo.document.Table.Header")
	proto.RegisterType((*Division)(nil), "mojo.document.Division")
	proto.RegisterType((*Blocks)(nil), "mojo.document.Blocks")
	proto.RegisterType((*Inline)(nil), "mojo.document.Inline")
	proto.RegisterType((*Text)(nil), "mojo.document.Text")
	proto.RegisterType((*Emphasized)(nil), "mojo.document.Emphasized")
	proto.RegisterType((*Strong)(nil), "mojo.document.Strong")
	proto.RegisterType((*Strikeout)(nil), "mojo.document.Strikeout")
	proto.RegisterType((*Superscript)(nil), "mojo.document.Superscript")
	proto.RegisterType((*Subscript)(nil), "mojo.document.Subscript")
	proto.RegisterType((*SmallCaps)(nil), "mojo.document.SmallCaps")
	proto.RegisterType((*Space)(nil), "mojo.document.Space")
	proto.RegisterType((*LineBreak)(nil), "mojo.document.LineBreak")
	proto.RegisterType((*Note)(nil), "mojo.document.Note")
	proto.RegisterType((*Quoted)(nil), "mojo.document.Quoted")
	proto.RegisterType((*Cite)(nil), "mojo.document.Cite")
	proto.RegisterType((*Citation)(nil), "mojo.document.Citation")
	proto.RegisterType((*Code)(nil), "mojo.document.Code")
	proto.RegisterType((*Link)(nil), "mojo.document.Link")
	proto.RegisterType((*Image)(nil), "mojo.document.Image")
	proto.RegisterType((*Span)(nil), "mojo.document.Span")
	proto.RegisterType((*Target)(nil), "mojo.document.Target")
	proto.RegisterType((*Inlines)(nil), "mojo.document.Inlines")
	proto.RegisterType((*MetaData)(nil), "mojo.document.MetaData")
	proto.RegisterMapType((map[string]*MetaValue)(nil), "mojo.document.MetaData.ValuesEntry")
	proto.RegisterType((*MetaValueObject)(nil), "mojo.document.MetaValueObject")
	proto.RegisterMapType((map[string]*MetaValue)(nil), "mojo.document.MetaValueObject.ValuesEntry")
	proto.RegisterType((*MetaValues)(nil), "mojo.document.MetaValues")
	proto.RegisterType((*MetaValue)(nil), "mojo.document.MetaValue")
}

func init() { proto.RegisterFile("mojo/document/document.proto", fileDescriptor_6211100ee17574eb) }

var fileDescriptor_6211100ee17574eb = []byte{
	// 2522 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x5a, 0x4b, 0x6f, 0x23, 0x59,
	0x15, 0xee, 0x8a, 0x1f, 0x89, 0x8f, 0xf3, 0xf0, 0xdc, 0xa4, 0x27, 0xee, 0x74, 0x7a, 0x1c, 0x6a,
	0x24, 0xd4, 0xa0, 0xc1, 0x11, 0x19, 0x09, 0x8d, 0x18, 0x40, 0xd8, 0x71, 0x75, 0xc7, 0xd3, 0x7e,
	0xc5, 0x76, 0x7a, 0xba, 0x67, 0x63, 0xca, 0xf6, 0x6d, 0xa7, 0x3a, 0xe5, 0x2a, 0x53, 0x75, 0xdd,
	0xdd, 0x81, 0x3f, 0xc0, 0x9e, 0x15, 0xe2, 0x29, 0x36, 0xf0, 0x03, 0xe0, 0x17, 0xf0, 0x07, 0xd8,
	0x21, 0x21, 0xe4, 0x35, 0xf2, 0x0a, 0xd6, 0x48, 0x08, 0xdd, 0x47, 0x3d, 0x6e, 0xb9, 0xec, 0x1e,
	0x0d, 0x06, 0x09, 0xb1, 0x4b, 0x7d, 0xe7, 0x9c, 0xef, 0x3e, 0xcf, 0xeb, 0xc6, 0x70, 0x3c, 0xb6,
	0x5f, 0xda, 0xa7, 0x43, 0x7b, 0x30, 0x1d, 0x63, 0x8b, 0xf8, 0x7f, 0x14, 0x27, 0x8e, 0x4d, 0x6c,
	0xb4, 0x43, 0xa5, 0x45, 0x0f, 0x3c, 0x3a, 0x60, 0xca, 0x03, 0xdb, 0xc1, 0xa7, 0xc4, 0x18, 0x63,
	0xae, 0x74, 0xb4, 0x1f, 0xa0, 0x53, 0xc7, 0x14, 0xe0, 0x03, 0x99, 0x57, 0x27, 0xc4, 0x31, 0xfa,
	0x53, 0x22, 0x6c, 0xd4, 0x9f, 0x29, 0xb0, 0x55, 0x11, 0x42, 0x54, 0x83, 0xcc, 0x18, 0x13, 0xbd,
	0x37, 0xd4, 0x89, 0x9e, 0x57, 0x4e, 0x94, 0x87, 0xd9, 0xb3, 0xc3, 0xa2, 0x34, 0x72, 0xb1, 0x8e,
	0x89, 0x5e, 0xd1, 0x89, 0x5e, 0x7e, 0x77, 0x3e, 0x2b, 0xa0, 0xb1, 0xf8, 0xfa, 0xc0, 0x1e, 0x1b,
	0x04, 0x8f, 0x27, 0xe4, 0xb6, 0xbd, 0xe5, 0x61, 0xa8, 0x0c, 0xe9, 0xbe, 0x69, 0x0f, 0x6e, 0xdc,
	0xfc, 0xc6, 0x49, 0xe2, 0x61, 0xf6, 0xec, 0x20, 0x42, 0x55, 0xa6, 0xc2, 0xf2, 0xc1, 0x7c, 0x56,
	0xc8, 0x71, 0xbd, 0x10, 0x8b, 0xb0, 0x54, 0x7f, 0xba, 0x09, 0x29, 0xa6, 0x87, 0x4a, 0x90, 0x9a,
	0x98, 0xba, 0x61, 0x89, 0x79, 0x45, 0xc9, 0x5a, 0x54, 0x56, 0xde, 0x9f, 0xcf, 0x0a, 0x7b, 0x4c,
	0x2d, 0xe0, 0xba, 0xb8, 0xd3, 0xe6, 0x96, 0xe8, 0x12, 0x32, 0x13, 0xdd, 0xd1, 0x47, 0x8e, 0x3e,
	0xb9, 0xce, 0x6f, 0x30, 0x9a, 0x7c, 0x94, 0xc6, 0x93, 0x97, 0x0f, 0xe7, 0xb3, 0xc2, 0xbe, 0xaf,
	0x2e, 0xd1, 0x05, 0x2c, 0xa8, 0x0d, 0x60, 0x1a, 0x16, 0xee, 0xb1, 0xe9, 0xe6, 0x13, 0xb1, 0x9c,
	0x35, 0xc3, 0xc2, 0x7c, 0xad, 0x8c, 0xd3, 0xf4, 0x3e, 0x65, 0x4e, 0x1f, 0xa6, 0x9c, 0x03, 0x7b,
	0xe8, 0x71, 0x26, 0x63, 0x39, 0xcf, 0xed, 0x61, 0x98, 0x73, 0xe0, 0x7d, 0xca, 0x9c, 0x3e, 0x8c,
	0x9e, 0x42, 0x96, 0xd1, 0xf5, 0xbe, 0x3f, 0xb5, 0x09, 0xce, 0xa7, 0x18, 0xe9, 0xbd, 0xb8, 0x03,
	0xb9, 0xa4, 0x0a, 0xe5, 0xfc, 0x7c, 0x56, 0x38, 0xe8, 0xfb, 0xdf, 0x12, 0x2d, 0x04, 0x38, 0xfa,
	0x0c, 0xb6, 0x6d, 0x67, 0x88, 0x1d, 0x3c, 0xec, 0x99, 0x86, 0x4b, 0xf2, 0x69, 0x46, 0x7c, 0x14,
	0x21, 0x6e, 0x72, 0x95, 0x9a, 0xe1, 0x92, 0xf2, 0xbd, 0xf9, 0xac, 0x70, 0xd7, 0x0e, 0x00, 0x89,
	0x3a, 0x1b, 0x12, 0xb0, 0x39, 0x4f, 0x4d, 0x13, 0x13, 0x4e, 0xbd, 0x19, 0x3f, 0x67, 0xa6, 0xc1,
	0x98, 0xf9, 0x9c, 0xfd, 0xef, 0xc8, 0x9c, 0x7d, 0x1c, 0xbd, 0x80, 0xbd, 0x21, 0x7e, 0x61, 0x58,
	0x06, 0x31, 0x6c, 0x8b, 0x73, 0x6f, 0x31, 0xee, 0x07, 0x11, 0xee, 0x8a, 0xaf, 0xc5, 0xf8, 0x8f,
	0xe7, 0xb3, 0x42, 0x7e, 0x28, 0x61, 0xd2, 0x18, 0xbb, 0xb2, 0x0c, 0x69, 0x90, 0xbe, 0xc6, 0xfa,
	0x10, 0x3b, 0xf9, 0x0c, 0xa3, 0xbf, 0x1b, 0xa1, 0xbf, 0x60, 0x42, 0xee, 0x00, 0x5c, 0x51, 0xa2,
	0x13, 0xc6, 0xf4, 0xe2, 0x13, 0xbd, 0x6f, 0xe2, 0x3c, 0xc4, 0x5e, 0xfc, 0x2e, 0x95, 0xf1, 0x8b,
	0xcf, 0xd4, 0xe4, 0x8b, 0xcf, 0x20, 0x54, 0x87, 0xad, 0xa1, 0xf1, 0xca, 0x70, 0x0d, 0xdb, 0xca,
	0x67, 0x63, 0xdd, 0xba, 0x22, 0xc4, 0xdc, 0xad, 0x3d, 0x65, 0x89, 0xcb, 0xa7, 0x28, 0x6f, 0x42,
	0x8a, 0x5d, 0x01, 0xf5, 0x09, 0x24, 0xe9, 0xe5, 0x46, 0xe7, 0x90, 0x7e, 0xa5, 0x9b, 0x53, 0xec,
	0xe6, 0x15, 0xe6, 0xe9, 0xd1, 0x95, 0x56, 0x2d, 0x76, 0xbb, 0xd9, 0x4a, 0xb9, 0x62, 0xd8, 0xd5,
	0x39, 0xa2, 0x36, 0x21, 0xc5, 0x9c, 0x18, 0x3d, 0x82, 0x4d, 0x83, 0x19, 0x78, 0x81, 0x63, 0x09,
	0xdd, 0xdd, 0xf9, 0xac, 0xf0, 0x8e, 0xd0, 0x0c, 0xf1, 0x79, 0xc6, 0x6a, 0x07, 0x32, 0xbe, 0x3b,
	0xaf, 0x8d, 0xf4, 0x09, 0x64, 0x7c, 0x7f, 0x46, 0xdf, 0x81, 0x54, 0x98, 0x72, 0x3f, 0xce, 0xf1,
	0xd9, 0xc9, 0x44, 0xe9, 0xb8, 0x99, 0xfa, 0x47, 0x05, 0x32, 0xbe, 0x27, 0xa3, 0x26, 0x64, 0xfc,
	0xe8, 0x2c, 0xa2, 0x5c, 0xd4, 0xed, 0x4b, 0x9e, 0x9c, 0xbb, 0xbd, 0xaf, 0x1e, 0xa2, 0x0e, 0x38,
	0xd0, 0x19, 0x6c, 0x99, 0xba, 0x35, 0x9a, 0xea, 0x23, 0xcc, 0xc2, 0x5d, 0x86, 0x9f, 0xae, 0x87,
	0x85, 0x83, 0xb6, 0x87, 0x05, 0x4b, 0x4a, 0x7c, 0xb1, 0x25, 0xb5, 0x00, 0x82, 0x30, 0xb2, 0x96,
	0x14, 0xf0, 0xf3, 0x14, 0xec, 0x50, 0x7f, 0xf2, 0xd7, 0x8e, 0xbe, 0x05, 0xdb, 0x7d, 0x3c, 0x32,
	0xac, 0x9e, 0x35, 0x1d, 0xf7, 0xb1, 0xc3, 0xf6, 0x2a, 0xc1, 0x03, 0x0b, 0xc3, 0x1b, 0x0c, 0x0e,
	0x51, 0x65, 0x43, 0x30, 0x7a, 0x01, 0xdb, 0xdc, 0xae, 0xe7, 0x92, 0x5b, 0x93, 0xef, 0xcc, 0xee,
	0xd9, 0xc3, 0x85, 0x85, 0x86, 0x46, 0x2c, 0x72, 0xd3, 0x0e, 0xd5, 0xe7, 0xe3, 0x58, 0x01, 0x10,
	0x1e, 0x27, 0x04, 0xa3, 0x57, 0x90, 0x13, 0xe3, 0x0c, 0xb1, 0x69, 0x50, 0x1d, 0x87, 0x25, 0x88,
	0xdd, 0xb3, 0x0f, 0x3e, 0xc7, 0x58, 0x15, 0xcf, 0xa6, 0xfc, 0x60, 0x3e, 0x2b, 0xdc, 0xb3, 0x64,
	0x30, 0x34, 0xe6, 0x5e, 0x44, 0xa4, 0xfe, 0x49, 0x81, 0x6c, 0x68, 0xbe, 0xe8, 0x18, 0xf2, 0x8d,
	0xab, 0x7a, 0x59, 0x6b, 0xf7, 0x3a, 0xdd, 0xe7, 0x35, 0xad, 0x77, 0xd5, 0xe8, 0xb4, 0xb4, 0xf3,
	0xea, 0xa3, 0xaa, 0x56, 0xc9, 0xdd, 0x41, 0x79, 0x38, 0x90, 0xa4, 0xda, 0xb3, 0x52, 0xbd, 0x55,
	0xd3, 0x72, 0xca, 0x82, 0xa4, 0xa2, 0x9d, 0x57, 0xeb, 0xa5, 0x5a, 0x6e, 0x63, 0x81, 0xb1, 0xd6,
	0xfc, 0x54, 0x6b, 0xf7, 0xda, 0xcd, 0x7a, 0xa9, 0x91, 0x4b, 0x2c, 0x8e, 0xd7, 0x6a, 0xf9, 0xd2,
	0xe4, 0x12, 0xdb, 0x52, 0xad, 0x75, 0x51, 0xca, 0xa5, 0x96, 0xd8, 0x72, 0x69, 0x5a, 0xfd, 0xb1,
	0x02, 0x7b, 0x91, 0xdd, 0x41, 0x27, 0x70, 0x2c, 0x2c, 0x2a, 0x5a, 0xad, 0x5a, 0xaf, 0x76, 0xb5,
	0x76, 0x64, 0x85, 0xf7, 0xe1, 0x70, 0x41, 0xa3, 0xa5, 0xb5, 0xab, 0xcd, 0x4a, 0x4e, 0x41, 0x05,
	0xb8, 0xbf, 0x20, 0x6c, 0x36, 0xb4, 0x5e, 0xab, 0xd4, 0xd6, 0x1a, 0xdd, 0xdc, 0x46, 0x2c, 0x7f,
	0xf7, 0xd3, 0xa6, 0x50, 0xe8, 0xe4, 0x12, 0xea, 0x3f, 0x15, 0xc8, 0x86, 0x12, 0x1c, 0xea, 0x2c,
	0xba, 0xf1, 0xf1, 0xaa, 0x03, 0xff, 0x5c, 0xae, 0x5c, 0x83, 0x14, 0x45, 0x3d, 0x3f, 0xfa, 0xd2,
	0xf2, 0x04, 0xcb, 0x7d, 0xca, 0xe5, 0x4e, 0xca, 0x6c, 0xc2, 0x4e, 0xca, 0x80, 0xa3, 0x1a, 0xa4,
	0xb9, 0x16, 0x75, 0x50, 0x29, 0x72, 0xaf, 0x70, 0xd0, 0xa5, 0x81, 0xfb, 0x37, 0x0a, 0x40, 0x90,
	0x86, 0xd1, 0x13, 0x79, 0xaa, 0x27, 0x4b, 0x13, 0xf6, 0x7f, 0x7f, 0xa6, 0xff, 0x50, 0x60, 0x57,
	0x4e, 0xea, 0xa8, 0x2e, 0xcf, 0x56, 0x5d, 0x59, 0x02, 0x14, 0xab, 0x04, 0x8f, 0x57, 0xce, 0xf7,
	0x27, 0x0a, 0x24, 0xa9, 0x12, 0xfa, 0x36, 0x24, 0x09, 0x76, 0xc6, 0xab, 0x13, 0x22, 0x9a, 0xcf,
	0x0a, 0xbb, 0x54, 0x2d, 0x44, 0xc4, 0xcc, 0x50, 0x1b, 0xb2, 0x41, 0x35, 0xb1, 0x2c, 0x65, 0x89,
	0xfd, 0x63, 0x01, 0x29, 0xa4, 0x1d, 0x0e, 0x48, 0x21, 0x58, 0xfd, 0x83, 0x02, 0x69, 0x5e, 0x73,
	0xac, 0x3f, 0xd5, 0x7c, 0x05, 0x52, 0x26, 0x7e, 0x85, 0x4d, 0x16, 0x4d, 0x13, 0x22, 0x43, 0x50,
	0x40, 0xca, 0x10, 0x14, 0xe0, 0x3b, 0xf3, 0x86, 0x88, 0x04, 0xb3, 0x7a, 0x67, 0xde, 0x10, 0x79,
	0x67, 0xde, 0x10, 0xf5, 0x77, 0x29, 0x48, 0xb1, 0x9a, 0x87, 0xa6, 0xf4, 0x81, 0x3e, 0xa1, 0x6b,
	0x5b, 0xbd, 0xcb, 0x2c, 0xa5, 0x0b, 0xcd, 0x70, 0x4a, 0x17, 0x10, 0xba, 0x82, 0x8c, 0x6e, 0x1a,
	0x23, 0x8b, 0xda, 0x88, 0x6c, 0xf0, 0x5e, 0x5c, 0x91, 0x55, 0x2c, 0x79, 0x5a, 0x62, 0x4b, 0xbc,
	0x4f, 0x69, 0x4b, 0x3c, 0x90, 0x6e, 0xc9, 0x6b, 0x63, 0x48, 0xae, 0x59, 0xd0, 0x57, 0xf8, 0x96,
	0x30, 0x20, 0xbc, 0x25, 0x0c, 0x40, 0x55, 0xbf, 0x52, 0xe4, 0xd5, 0xfe, 0xfd, 0xd8, 0xe1, 0x57,
	0xd5, 0x8b, 0x7e, 0xb5, 0xf8, 0x5d, 0x48, 0x3a, 0xf6, 0x6b, 0x37, 0x9f, 0x62, 0x3b, 0x92, 0x8f,
	0x25, 0x6a, 0xdb, 0xaf, 0xf9, 0x06, 0x53, 0xcd, 0xf0, 0x06, 0xd3, 0xef, 0xa3, 0x4f, 0x20, 0x79,
	0x8e, 0x4d, 0x73, 0x1d, 0x0e, 0x77, 0xd4, 0x80, 0x44, 0xdb, 0x7e, 0x8d, 0x1e, 0x47, 0xa8, 0xee,
	0xc5, 0x4e, 0x8b, 0x8e, 0xfa, 0x16, 0xbe, 0x4b, 0xff, 0x06, 0xaf, 0x8b, 0x52, 0xc5, 0x90, 0xf1,
	0xcf, 0x15, 0xdd, 0x83, 0xbb, 0xa5, 0x5a, 0xf5, 0x71, 0xa3, 0xae, 0x35, 0xba, 0x91, 0x34, 0x82,
	0x60, 0x37, 0x10, 0xd5, 0xb4, 0x47, 0xdd, 0x9c, 0x82, 0xf6, 0x61, 0x2f, 0xc0, 0xda, 0xd5, 0xc7,
	0x17, 0x34, 0x63, 0x1c, 0x40, 0x2e, 0x00, 0xcf, 0xb5, 0x46, 0x57, 0x6b, 0xe7, 0x12, 0xea, 0xaf,
	0x69, 0x9f, 0x2d, 0x0a, 0xe8, 0xf5, 0xbb, 0x9f, 0x06, 0x9b, 0x03, 0xdb, 0x22, 0xfc, 0x02, 0x2f,
	0x3f, 0x2c, 0xee, 0x09, 0x5c, 0x51, 0xf2, 0x04, 0x0e, 0xa9, 0xeb, 0x8d, 0xb6, 0xbf, 0xca, 0x40,
	0x9a, 0xbb, 0xa0, 0xef, 0xf3, 0x7c, 0xad, 0xd1, 0xa2, 0xb2, 0x8b, 0xdf, 0x90, 0x38, 0x8f, 0xbf,
	0xb8, 0xc3, 0x7d, 0x1e, 0x5d, 0x01, 0xe0, 0xf1, 0xe4, 0x5a, 0x77, 0x8d, 0x1f, 0xe0, 0xa1, 0xe8,
	0xdc, 0xa3, 0x07, 0xae, 0xf9, 0x0a, 0xbc, 0x11, 0x0c, 0x0c, 0xe4, 0x46, 0x30, 0xc0, 0x69, 0x83,
	0xe6, 0x12, 0xc7, 0xb6, 0x46, 0xa2, 0x71, 0x8f, 0xc6, 0x8f, 0x0e, 0x13, 0xf2, 0x55, 0x72, 0x45,
	0xb9, 0x41, 0xe3, 0x18, 0xba, 0x84, 0x8c, 0x4b, 0x1c, 0xe3, 0x06, 0xdb, 0x53, 0xb2, 0xa4, 0x5d,
	0xef, 0x78, 0x72, 0x7e, 0x9a, 0xbe, 0xba, 0xdc, 0xae, 0xfb, 0x30, 0x7a, 0x0e, 0x59, 0x77, 0x3a,
	0xc1, 0x8e, 0x3b, 0x70, 0x8c, 0x09, 0x11, 0xed, 0x7a, 0xb4, 0xab, 0xee, 0x04, 0x1a, 0x3c, 0x07,
	0x84, 0x4c, 0xe4, 0xae, 0x3a, 0x24, 0x60, 0xb3, 0x9d, 0xf6, 0x05, 0x71, 0x3a, 0x7e, 0xb6, 0x9e,
	0x5c, 0xcc, 0xd6, 0xfb, 0x8c, 0xcc, 0xd6, 0x83, 0x51, 0x1b, 0xc0, 0x1d, 0xeb, 0xa6, 0xd9, 0x1b,
	0xe8, 0x13, 0x57, 0xf4, 0xe9, 0x0b, 0x9c, 0x54, 0xe1, 0x5c, 0x9f, 0xb8, 0x82, 0xd3, 0xfb, 0x8c,
	0x70, 0x7a, 0x30, 0x3d, 0x1b, 0xf6, 0x54, 0x31, 0x14, 0xbd, 0x79, 0xf4, 0x6c, 0x58, 0x7f, 0x31,
	0xe4, 0x67, 0xc3, 0x15, 0xe5, 0xb3, 0xe1, 0x18, 0xbd, 0x78, 0x03, 0x83, 0x60, 0xd1, 0x81, 0x47,
	0x2f, 0xde, 0xb9, 0x41, 0x44, 0xaa, 0xa1, 0x4a, 0xf2, 0xc5, 0xa3, 0x08, 0x33, 0xb7, 0x87, 0x5e,
	0xeb, 0xbd, 0x1f, 0xf7, 0x08, 0xc3, 0xcd, 0xed, 0x61, 0xd4, 0xdc, 0x1e, 0x62, 0xda, 0xba, 0xbb,
	0x13, 0x7d, 0x80, 0x45, 0xd3, 0x1d, 0x75, 0xa2, 0x0e, 0x95, 0xf1, 0xc4, 0xc0, 0xd4, 0xe4, 0xd6,
	0x9d, 0x41, 0xc1, 0x03, 0x93, 0x83, 0xf5, 0x9b, 0xfc, 0xf6, 0xf2, 0x07, 0x26, 0x2a, 0x0f, 0x3d,
	0x30, 0xd1, 0xcf, 0x98, 0x07, 0x26, 0x0a, 0xd3, 0x55, 0x99, 0x86, 0x75, 0x93, 0xdf, 0x89, 0x5d,
	0x55, 0xcd, 0xb0, 0x6e, 0xf8, 0xaa, 0xa8, 0x92, 0xbc, 0x2a, 0x8a, 0xd0, 0x55, 0x19, 0x63, 0xda,
	0x53, 0xee, 0xc6, 0xae, 0xaa, 0x4a, 0x65, 0xa2, 0x48, 0x1a, 0x4b, 0x6d, 0x26, 0x5d, 0x15, 0x83,
	0xe8, 0x0c, 0x2c, 0x9b, 0xe0, 0xfc, 0x5e, 0xec, 0x0c, 0x1a, 0xb6, 0x77, 0x2c, 0x56, 0xf4, 0xed,
	0x89, 0x99, 0x51, 0x73, 0x77, 0xa2, 0x5b, 0xf9, 0x5c, 0xac, 0x79, 0x67, 0xa2, 0x5b, 0xdc, 0x9c,
	0x2a, 0xc9, 0xe6, 0x14, 0x29, 0x6f, 0x41, 0x9a, 0xb7, 0xf3, 0xea, 0xd7, 0x21, 0x49, 0x83, 0x0f,
	0xcd, 0xd5, 0x2c, 0x68, 0xb1, 0x00, 0x95, 0xe1, 0x93, 0x67, 0x40, 0x38, 0x57, 0x33, 0x40, 0xbd,
	0x04, 0x08, 0x42, 0xcd, 0x7a, 0x5e, 0x3e, 0xea, 0x90, 0xe6, 0xa1, 0x66, 0x3d, 0x74, 0x2d, 0xc8,
	0xf8, 0xf1, 0x66, 0x3d, 0x8c, 0x6d, 0xc8, 0x86, 0x82, 0xcd, 0xfa, 0x66, 0xe9, 0x47, 0x90, 0xb5,
	0x31, 0xfa, 0xf1, 0x63, 0x2d, 0x8c, 0x9b, 0x90, 0x62, 0x3e, 0xaa, 0x66, 0xc5, 0xab, 0x0f, 0x75,
	0x1f, 0xf5, 0x13, 0x48, 0x36, 0xc4, 0xe3, 0xc6, 0xbf, 0x9d, 0x23, 0x7f, 0xaf, 0x40, 0x9a, 0x87,
	0x32, 0x54, 0x86, 0x24, 0xb9, 0x9d, 0xf0, 0x2b, 0xb8, 0xbb, 0x10, 0xec, 0xb9, 0x52, 0xb1, 0x7b,
	0x3b, 0xf1, 0x8a, 0xe3, 0xdb, 0x09, 0x96, 0x8a, 0xe3, 0xdb, 0x49, 0x90, 0x67, 0x37, 0xbe, 0x58,
	0x6d, 0xfd, 0x10, 0x92, 0x74, 0x00, 0xb4, 0x07, 0xd9, 0xee, 0xf3, 0x96, 0xd6, 0xab, 0x34, 0xaf,
	0xca, 0x35, 0x2d, 0x77, 0xc7, 0x07, 0x3a, 0xd5, 0xc6, 0xe3, 0x9a, 0x96, 0x53, 0xd4, 0x5f, 0x28,
	0x90, 0xa4, 0xd1, 0x13, 0x35, 0x20, 0x33, 0x30, 0x88, 0xce, 0xdb, 0x14, 0xbe, 0x0f, 0x87, 0x8b,
	0x51, 0x96, 0xc9, 0xc5, 0x53, 0xb5, 0xa7, 0x1d, 0xae, 0x64, 0x7c, 0x70, 0x6d, 0xef, 0x74, 0xbf,
	0x4d, 0xc0, 0x96, 0x37, 0x30, 0x3a, 0x81, 0x0d, 0x63, 0x28, 0x7c, 0x3b, 0x37, 0x9f, 0x15, 0xb6,
	0x8d, 0x50, 0xb6, 0x68, 0x6f, 0x18, 0xcc, 0x8f, 0x27, 0x0e, 0x7e, 0x61, 0xbc, 0x59, 0x3d, 0x2a,
	0x3b, 0x4c, 0xae, 0x18, 0x3e, 0x4c, 0x8e, 0x50, 0x12, 0x77, 0xfa, 0x82, 0x92, 0x24, 0xde, 0x4a,
	0xc2, 0x15, 0xc3, 0x24, 0x1c, 0x41, 0x15, 0x48, 0x8e, 0x69, 0xca, 0x49, 0xb2, 0x6b, 0x70, 0xbc,
	0x64, 0x2f, 0x8b, 0x75, 0x3f, 0xf7, 0x8c, 0xa5, 0xdc, 0xd3, 0x66, 0xd6, 0xe8, 0x1b, 0x00, 0x34,
	0x52, 0xf6, 0x06, 0xf6, 0xd4, 0xe2, 0xf5, 0x43, 0x82, 0x6f, 0x3f, 0x45, 0xcf, 0x29, 0x18, 0xde,
	0x7e, 0x1f, 0x44, 0x5f, 0x86, 0xe4, 0xb5, 0xee, 0x5e, 0xb3, 0xc2, 0x20, 0xc1, 0xf9, 0xe9, 0x77,
	0x98, 0x9f, 0x7e, 0x53, 0x1f, 0xa0, 0x33, 0xa0, 0x17, 0xa3, 0xde, 0xac, 0x68, 0xbd, 0x46, 0xb3,
	0x5d, 0x2f, 0xd5, 0x72, 0x77, 0xd0, 0x21, 0xec, 0x33, 0xa0, 0x74, 0xd5, 0xbd, 0x68, 0xb6, 0x7b,
	0xd5, 0x46, 0xaf, 0xab, 0x3d, 0xeb, 0xf2, 0xe7, 0x24, 0x26, 0xe8, 0x5c, 0xb5, 0x5a, 0x6d, 0xad,
	0xd3, 0x11, 0x1a, 0xb9, 0x0d, 0xf5, 0x47, 0xf4, 0x2e, 0x51, 0xb2, 0xb5, 0x97, 0xc5, 0xa7, 0xe1,
	0xb2, 0x98, 0x1e, 0xfe, 0xdb, 0x0a, 0xe0, 0xbf, 0x29, 0xec, 0x45, 0xfb, 0x3f, 0xf0, 0x16, 0xcb,
	0x1a, 0x7a, 0x1e, 0xed, 0x68, 0xc3, 0xba, 0xf2, 0x96, 0x89, 0x86, 0xde, 0xd7, 0x96, 0x1b, 0x7a,
	0x1f, 0xa6, 0xf7, 0x8d, 0xe8, 0xce, 0x08, 0x93, 0x25, 0xf5, 0x6b, 0x97, 0x09, 0xf9, 0x7d, 0xe3,
	0x8a, 0xe1, 0xfb, 0xc6, 0x11, 0xf5, 0xef, 0x0a, 0xa4, 0x58, 0xca, 0xfe, 0x3f, 0x5a, 0xf3, 0x2f,
	0x15, 0x48, 0xd2, 0x2a, 0x61, 0xfd, 0x4b, 0x5e, 0x57, 0xf8, 0xba, 0x86, 0x34, 0x5f, 0x09, 0x2d,
	0x4d, 0x88, 0x41, 0x4c, 0xa9, 0x34, 0x61, 0x40, 0xb8, 0x34, 0x61, 0x00, 0xfa, 0x10, 0x12, 0x53,
	0xc7, 0x14, 0xfd, 0xd1, 0x2e, 0x1f, 0x78, 0x60, 0x3b, 0xb8, 0x78, 0xe5, 0x98, 0xe5, 0x77, 0xe6,
	0xb3, 0xc2, 0xce, 0xd4, 0x09, 0x3f, 0xc8, 0x50, 0x6d, 0xb5, 0x01, 0x9b, 0x7c, 0x4e, 0x6b, 0xca,
	0x99, 0x7f, 0x56, 0x60, 0xcb, 0xfb, 0x27, 0x31, 0xba, 0x8c, 0x30, 0xbe, 0xbf, 0xe4, 0xbf, 0xc9,
	0xc5, 0xa7, 0x4c, 0x4b, 0xb3, 0x88, 0x73, 0xfb, 0x96, 0x27, 0x80, 0x1f, 0x42, 0x36, 0xa4, 0x8c,
	0xde, 0x87, 0xc4, 0x0d, 0xbe, 0x15, 0x9b, 0xc3, 0xd6, 0x78, 0x83, 0x6f, 0xc3, 0x6b, 0xbc, 0xc1,
	0xb7, 0xe8, 0xdc, 0x2b, 0xef, 0xe2, 0xff, 0xe9, 0x4b, 0x67, 0xc1, 0x38, 0x57, 0x15, 0x7e, 0xdf,
	0xdc, 0xf8, 0x48, 0x51, 0xff, 0xaa, 0xc0, 0x9e, 0xaf, 0xdd, 0xec, 0xbf, 0xc4, 0x03, 0x82, 0x9e,
	0x45, 0xd6, 0xf8, 0xd5, 0x65, 0xec, 0x5c, 0xff, 0x7f, 0x65, 0xa9, 0x5d, 0x00, 0x5f, 0x99, 0xa6,
	0x65, 0x79, 0x91, 0xcb, 0x79, 0x57, 0xdf, 0x8e, 0xbf, 0x24, 0x21, 0xe3, 0xeb, 0xa2, 0x29, 0xdc,
	0x65, 0xbf, 0x37, 0x60, 0xc2, 0x9e, 0xcd, 0xf6, 0x87, 0x7e, 0x08, 0x57, 0x7c, 0x6f, 0xf5, 0x4e,
	0x96, 0x4f, 0xe6, 0xb3, 0xc2, 0xf1, 0x58, 0x06, 0x9f, 0xea, 0xa6, 0x54, 0xf1, 0xa3, 0x45, 0x39,
	0xfa, 0x1e, 0xec, 0x05, 0xc3, 0xba, 0x6c, 0xc0, 0xf8, 0x37, 0x85, 0x60, 0x03, 0xca, 0xf7, 0xe7,
	0xb3, 0xc2, 0xa1, 0xcf, 0xe5, 0x46, 0x87, 0xd9, 0x91, 0x44, 0xe8, 0x0c, 0xb6, 0xfa, 0xb6, 0x6d,
	0x32, 0x6a, 0x1a, 0xa7, 0xb6, 0xb8, 0xc3, 0x53, 0x2c, 0x6a, 0xb9, 0x29, 0x40, 0xf4, 0x11, 0x80,
	0x4b, 0x1c, 0xc3, 0x1a, 0x31, 0xab, 0x24, 0x3b, 0x65, 0xff, 0xb5, 0xc0, 0x1a, 0x45, 0xed, 0x32,
	0x3e, 0x8c, 0xba, 0xb0, 0x33, 0xd4, 0x09, 0xee, 0x11, 0x63, 0x8c, 0x99, 0xb1, 0xd4, 0xae, 0xb2,
	0x08, 0x50, 0xd1, 0x09, 0xee, 0x1a, 0x63, 0x2f, 0xce, 0x8a, 0xaf, 0x28, 0x67, 0x36, 0x24, 0x40,
	0x1d, 0xc8, 0x8a, 0x68, 0xc4, 0x38, 0x79, 0xb3, 0xf7, 0x6e, 0x6c, 0x48, 0x70, 0xf9, 0x93, 0x8b,
	0x50, 0x8f, 0xb2, 0x42, 0x80, 0xa3, 0x26, 0xf0, 0x5f, 0x0f, 0x70, 0xce, 0xbd, 0xd8, 0x10, 0x2e,
	0x9e, 0xb5, 0xd9, 0xda, 0xb9, 0xf2, 0xc2, 0xda, 0x7d, 0xb8, 0xbc, 0x0d, 0x10, 0x9c, 0x65, 0xf9,
	0x25, 0x1c, 0xd9, 0xce, 0x88, 0xf1, 0x99, 0xba, 0x35, 0x92, 0x89, 0xcb, 0x3b, 0xde, 0x0f, 0x5d,
	0x5a, 0x8e, 0x4d, 0xec, 0x96, 0xf2, 0xd9, 0xc7, 0x23, 0x83, 0x5c, 0x4f, 0xfb, 0xc5, 0x81, 0x3d,
	0x3e, 0xa5, 0xaa, 0x5f, 0xa3, 0x46, 0xc1, 0x6f, 0x65, 0x46, 0xf6, 0xe9, 0xe4, 0x66, 0x74, 0x2a,
	0xfd, 0x80, 0xe6, 0x63, 0xef, 0x8f, 0x7e, 0x9a, 0xfd, 0x80, 0xe6, 0xc3, 0x7f, 0x05, 0x00, 0x00,
	0xff, 0xff, 0x73, 0xbf, 0x76, 0x17, 0xb9, 0x23, 0x00, 0x00,
}
