// Code generated by wand. DO NOT EDIT.
// Rerunning wand will overwrite this file.
//
// Copyright 2021 Mojo-lang.org
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package document

import (
	"strconv"
)

var TableAlignmentNames = map[int32]string{
	1: "left",
	2: "right",
	3: "center",
}

var TableAlignmentValues = map[string]Table_Alignment{
	"left":   Table_ALIGNMENT_LEFT,
	"right":  Table_ALIGNMENT_RIGHT,
	"center": Table_ALIGNMENT_CENTER,
}

func (x Table_Alignment) Format() string {
	s, ok := TableAlignmentNames[int32(x)]
	if ok {
		return s
	}
	if int(x) == 0 {
		return "unspecified"
	}
	return strconv.Itoa(int(x))
}

func (x *Table_Alignment) Parse(value string) {
	if x != nil {
		s, ok := TableAlignmentValues[value]
		if ok {
			*x = s
		} else {
			*x = Table_ALIGNMENT_LEFT
		}
	} else {
		*x = Table_ALIGNMENT_LEFT
	}
}
