// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/document/document.proto

package org.mojolang.mojo.document;

public interface BlocksOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.document.Blocks)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .mojo.document.Block values = 1;</code>
   */
  java.util.List<org.mojolang.mojo.document.Block> 
      getValuesList();
  /**
   * <code>repeated .mojo.document.Block values = 1;</code>
   */
  org.mojolang.mojo.document.Block getValues(int index);
  /**
   * <code>repeated .mojo.document.Block values = 1;</code>
   */
  int getValuesCount();
  /**
   * <code>repeated .mojo.document.Block values = 1;</code>
   */
  java.util.List<? extends org.mojolang.mojo.document.BlockOrBuilder> 
      getValuesOrBuilderList();
  /**
   * <code>repeated .mojo.document.Block values = 1;</code>
   */
  org.mojolang.mojo.document.BlockOrBuilder getValuesOrBuilder(
      int index);
}
