// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/document/document.proto

package org.mojolang.mojo.document;

public final class DocumentProto {
  private DocumentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_Document_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_Document_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_Block_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_Block_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_Line_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_Line_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_Plain_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_Plain_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_Paragraph_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_Paragraph_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_LineBlock_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_LineBlock_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_CodeBlock_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_CodeBlock_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_QuoteBlock_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_QuoteBlock_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_ListAttribute_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_ListAttribute_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_OrderedList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_OrderedList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_OrderedList_Blocks_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_OrderedList_Blocks_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_BulletList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_BulletList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_BulletList_Blocks_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_BulletList_Blocks_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_DefinitionList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_DefinitionList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_DefinitionList_Item_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_DefinitionList_Item_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_Header_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_Header_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_Table_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_Table_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_Table_Cell_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_Table_Cell_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_Table_Row_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_Table_Row_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_Table_Header_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_Table_Header_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_Division_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_Division_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_Blocks_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_Blocks_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_Inline_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_Inline_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_Text_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_Text_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_Emphasized_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_Emphasized_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_Strong_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_Strong_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_Strikeout_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_Strikeout_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_Superscript_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_Superscript_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_Subscript_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_Subscript_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_SmallCaps_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_SmallCaps_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_Space_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_Space_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_LineBreak_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_LineBreak_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_Note_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_Note_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_Quoted_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_Quoted_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_Cite_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_Cite_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_Citation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_Citation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_Code_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_Code_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_Link_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_Link_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_Image_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_Image_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_Span_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_Span_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_Target_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_Target_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_Inlines_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_Inlines_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_MetaData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_MetaData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_MetaData_ValuesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_MetaData_ValuesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_MetaValueObject_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_MetaValueObject_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_MetaValueObject_ValuesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_MetaValueObject_ValuesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_MetaValues_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_MetaValues_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_document_MetaValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_document_MetaValue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034mojo/document/document.proto\022\rmojo.doc" +
      "ument\032\024mojo/core/time.proto\032\023mojo/core/u" +
      "rl.proto\032\035mojo/document/attribute.proto\"" +
      "\\\n\010Document\022*\n\tmeta_data\030\001 \001(\0132\027.mojo.do" +
      "cument.MetaData\022$\n\006blocks\030\002 \003(\0132\024.mojo.d" +
      "ocument.Block\"\225\004\n\005Block\022%\n\005plain\030\001 \001(\0132\024" +
      ".mojo.document.PlainH\000\022-\n\tparagraph\030\002 \001(" +
      "\0132\030.mojo.document.ParagraphH\000\022.\n\nline_bl" +
      "ock\030\003 \001(\0132\030.mojo.document.LineBlockH\000\022.\n" +
      "\ncode_block\030\004 \001(\0132\030.mojo.document.CodeBl" +
      "ockH\000\0220\n\013quote_block\030\005 \001(\0132\031.mojo.docume" +
      "nt.QuoteBlockH\000\0222\n\014ordered_list\030\006 \001(\0132\032." +
      "mojo.document.OrderedListH\000\0220\n\013bullet_li" +
      "st\030\007 \001(\0132\031.mojo.document.BulletListH\000\0228\n" +
      "\017definition_list\030\010 \001(\0132\035.mojo.document.D" +
      "efinitionListH\000\022\'\n\006header\030\t \001(\0132\025.mojo.d" +
      "ocument.HeaderH\000\022%\n\005table\030\n \001(\0132\024.mojo.d" +
      "ocument.TableH\000\022+\n\010division\030\013 \001(\0132\027.mojo" +
      ".document.DivisionH\000B\007\n\005block\"-\n\004Line\022%\n" +
      "\006values\030\001 \003(\0132\025.mojo.document.Inline\"/\n\005" +
      "Plain\022&\n\007inlines\030\002 \003(\0132\025.mojo.document.I" +
      "nline\"3\n\tParagraph\022&\n\007inlines\030\002 \003(\0132\025.mo" +
      "jo.document.Inline\"/\n\tLineBlock\022\"\n\005lines" +
      "\030\002 \003(\0132\023.mojo.document.Line\"n\n\tCodeBlock" +
      "\022+\n\tattribute\030\001 \001(\0132\030.mojo.document.Attr" +
      "ibute\022\020\n\010language\030\002 \001(\t\022\"\n\005lines\030\003 \003(\0132\023" +
      ".mojo.document.Line\"2\n\nQuoteBlock\022$\n\006blo" +
      "cks\030\002 \003(\0132\024.mojo.document.Block\"\235\004\n\rList" +
      "Attribute\022\024\n\014begin_number\030\001 \001(\003\022>\n\014numbe" +
      "r_style\030\002 \001(\0162(.mojo.document.ListAttrib" +
      "ute.NumberStyle\022F\n\020number_delimiter\030\003 \001(" +
      "\0162,.mojo.document.ListAttribute.NumberDe" +
      "limiter\"\327\001\n\013NumberStyle\022\034\n\030NUMBER_STYLE_" +
      "UNSPECIFIED\020\000\022\030\n\024NUMBER_STYLE_EXAMPLE\020\001\022" +
      "\030\n\024NUMBER_STYLE_DECIMAL\020\002\022\034\n\030NUMBER_STYL" +
      "E_LOWER_ROMAN\020\003\022\034\n\030NUMBER_STYLE_UPPER_RO" +
      "MAN\020\004\022\034\n\030NUMBER_STYLE_LOWER_ALPHA\020\005\022\034\n\030N" +
      "UMBER_STYLE_UPPER_ALPHA\020\006\"\223\001\n\017NumberDeli" +
      "miter\022 \n\034NUMBER_DELIMITER_UNSPECIFIED\020\000\022" +
      "\033\n\027NUMBER_DELIMITER_PERIOD\020\001\022\037\n\033NUMBER_D" +
      "ELIMITER_ONE_PARENT\020\002\022 \n\034NUMBER_DELIMITE" +
      "R_TWO_PARENTS\020\003\"\240\001\n\013OrderedList\022/\n\tattri" +
      "bute\030\001 \001(\0132\034.mojo.document.ListAttribute" +
      "\0220\n\005items\030\002 \003(\0132!.mojo.document.OrderedL" +
      "ist.Blocks\032.\n\006Blocks\022$\n\006values\030\001 \003(\0132\024.m" +
      "ojo.document.Block\"m\n\nBulletList\022/\n\005item" +
      "s\030\002 \003(\0132 .mojo.document.BulletList.Block" +
      "s\032.\n\006Blocks\022$\n\006values\030\001 \003(\0132\024.mojo.docum" +
      "ent.Block\"\234\001\n\016DefinitionList\0221\n\005items\030\002 " +
      "\003(\0132\".mojo.document.DefinitionList.Item\032" +
      "W\n\004Item\022#\n\004term\030\001 \003(\0132\025.mojo.document.In" +
      "line\022*\n\013definitions\030\002 \003(\0132\025.mojo.documen" +
      "t.Blocks\"i\n\006Header\022+\n\tattribute\030\001 \001(\0132\030." +
      "mojo.document.Attribute\022\r\n\005level\030\002 \001(\003\022#" +
      "\n\004text\030\003 \003(\0132\025.mojo.document.Inline\"\302\003\n\005" +
      "Table\022&\n\007caption\030\001 \003(\0132\025.mojo.document.I" +
      "nline\0221\n\talignment\030\002 \001(\0162\036.mojo.document" +
      ".Table.Alignment\022\r\n\005width\030\003 \001(\001\022+\n\006heade" +
      "r\030\004 \001(\0132\033.mojo.document.Table.Header\022&\n\004" +
      "rows\030\005 \003(\0132\030.mojo.document.Table.Row\032,\n\004" +
      "Cell\022$\n\006values\030\001 \003(\0132\024.mojo.document.Blo" +
      "ck\0320\n\003Row\022)\n\006values\030\001 \003(\0132\031.mojo.documen" +
      "t.Table.Cell\0323\n\006Header\022)\n\006values\030\001 \003(\0132\031" +
      ".mojo.document.Table.Cell\"e\n\tAlignment\022\031" +
      "\n\025ALIGNMENT_UNSPECIFIED\020\000\022\022\n\016ALIGNMENT_L" +
      "EFT\020\001\022\023\n\017ALIGNMENT_RIGHT\020\002\022\024\n\020ALIGNMENT_" +
      "CENTER\020\003\"^\n\010Division\022+\n\tattribute\030\001 \001(\0132" +
      "\030.mojo.document.Attribute\022%\n\007content\030\002 \003" +
      "(\0132\024.mojo.document.Block\".\n\006Blocks\022$\n\006va" +
      "lues\030\001 \003(\0132\024.mojo.document.Block\"\262\005\n\006Inl" +
      "ine\022#\n\004text\030\001 \001(\0132\023.mojo.document.TextH\000" +
      "\022/\n\nemphasized\030\002 \001(\0132\031.mojo.document.Emp" +
      "hasizedH\000\022\'\n\006strong\030\003 \001(\0132\025.mojo.documen" +
      "t.StrongH\000\022-\n\tstrikeout\030\004 \001(\0132\030.mojo.doc" +
      "ument.StrikeoutH\000\0221\n\013superscript\030\005 \001(\0132\032" +
      ".mojo.document.SuperscriptH\000\022-\n\tsubscrip" +
      "t\030\006 \001(\0132\030.mojo.document.SubscriptH\000\022.\n\ns" +
      "mall_caps\030\007 \001(\0132\030.mojo.document.SmallCap" +
      "sH\000\022\'\n\006quoted\030\010 \001(\0132\025.mojo.document.Quot" +
      "edH\000\022#\n\004cite\030\t \001(\0132\023.mojo.document.CiteH" +
      "\000\022#\n\004code\030\n \001(\0132\023.mojo.document.CodeH\000\022%" +
      "\n\005space\030\013 \001(\0132\024.mojo.document.SpaceH\000\022.\n" +
      "\nline_break\030\014 \001(\0132\030.mojo.document.LineBr" +
      "eakH\000\022#\n\004link\030\r \001(\0132\023.mojo.document.Link" +
      "H\000\022%\n\005image\030\016 \001(\0132\024.mojo.document.ImageH" +
      "\000\022#\n\004note\030\017 \001(\0132\023.mojo.document.NoteH\000\022#" +
      "\n\004span\030\020 \001(\0132\023.mojo.document.SpanH\000B\010\n\006i" +
      "nline\"\025\n\004Text\022\r\n\005value\030\001 \001(\t\"3\n\nEmphasiz" +
      "ed\022%\n\006values\030\001 \003(\0132\025.mojo.document.Inlin" +
      "e\"/\n\006Strong\022%\n\006values\030\001 \003(\0132\025.mojo.docum" +
      "ent.Inline\"2\n\tStrikeout\022%\n\006values\030\001 \003(\0132" +
      "\025.mojo.document.Inline\"4\n\013Superscript\022%\n" +
      "\006values\030\001 \003(\0132\025.mojo.document.Inline\"2\n\t" +
      "Subscript\022%\n\006values\030\001 \003(\0132\025.mojo.documen" +
      "t.Inline\"2\n\tSmallCaps\022%\n\006values\030\001 \003(\0132\025." +
      "mojo.document.Inline\"\007\n\005Space\"\013\n\tLineBre" +
      "ak\",\n\004Note\022$\n\006values\030\001 \003(\0132\024.mojo.docume" +
      "nt.Block\"\201\001\n\006Quoted\022(\n\004type\030\001 \001(\0162\032.mojo" +
      ".document.Quoted.Type\022#\n\004text\030\002 \003(\0132\025.mo" +
      "jo.document.Inline\"(\n\004Type\022\017\n\013TYPE_DOUBL" +
      "E\020\000\022\017\n\013TYPE_SINGLE\020\001\"Z\n\004Cite\022*\n\tcitation" +
      "s\030\001 \003(\0132\027.mojo.document.Citation\022&\n\007inli" +
      "nes\030\002 \003(\0132\025.mojo.document.Inline\"\376\001\n\010Cit" +
      "ation\022\n\n\002id\030\001 \001(\t\022%\n\006prefix\030\002 \003(\0132\025.mojo" +
      ".document.Inline\022%\n\006suffix\030\003 \003(\0132\025.mojo." +
      "document.Inline\022*\n\004mode\030\004 \001(\0162\034.mojo.doc" +
      "ument.Citation.Mode\022\022\n\nnote_count\030\005 \001(\003\022" +
      "\014\n\004hash\030\006 \001(\003\"J\n\004Mode\022\017\n\013MODE_NORMAL\020\000\022\027" +
      "\n\023MODE_AUTHOR_IN_TEXT\020\001\022\030\n\024MODE_SUPPRESS" +
      "_AUTHOR\020\002\"D\n\004Code\022+\n\tattribute\030\001 \001(\0132\030.m" +
      "ojo.document.Attribute\022\017\n\007content\030\002 \001(\t\"" +
      "\206\001\n\004Link\022+\n\tattribute\030\001 \001(\0132\030.mojo.docum" +
      "ent.Attribute\022*\n\013description\030\002 \003(\0132\025.moj" +
      "o.document.Inline\022%\n\006target\030\003 \001(\0132\025.mojo" +
      ".document.Target\"\207\001\n\005Image\022+\n\tattribute\030" +
      "\001 \001(\0132\030.mojo.document.Attribute\022*\n\013descr" +
      "iption\030\002 \003(\0132\025.mojo.document.Inline\022%\n\006t" +
      "arget\030\003 \001(\0132\025.mojo.document.Target\"[\n\004Sp" +
      "an\022+\n\tattribute\030\001 \001(\0132\030.mojo.document.At" +
      "tribute\022&\n\007inlines\030\002 \003(\0132\025.mojo.document" +
      ".Inline\"4\n\006Target\022\r\n\005title\030\001 \001(\t\022\033\n\003url\030" +
      "\002 \001(\0132\016.mojo.core.Url\"0\n\007Inlines\022%\n\006valu" +
      "es\030\001 \003(\0132\025.mojo.document.Inline\"\210\001\n\010Meta" +
      "Data\0223\n\006values\030\001 \003(\0132#.mojo.document.Met" +
      "aData.ValuesEntry\032G\n\013ValuesEntry\022\013\n\003key\030" +
      "\001 \001(\t\022\'\n\005value\030\002 \001(\0132\030.mojo.document.Met" +
      "aValue:\0028\001\"\226\001\n\017MetaValueObject\022:\n\006values" +
      "\030\001 \003(\0132*.mojo.document.MetaValueObject.V" +
      "aluesEntry\032G\n\013ValuesEntry\022\013\n\003key\030\001 \001(\t\022\'" +
      "\n\005value\030\002 \001(\0132\030.mojo.document.MetaValue:" +
      "\0028\001\"6\n\nMetaValues\022(\n\006values\030\001 \003(\0132\030.mojo" +
      ".document.MetaValue\"\304\002\n\tMetaValue\022?\n\025met" +
      "a_value_object_val\030\001 \001(\0132\036.mojo.document" +
      ".MetaValueObjectH\000\0224\n\017meta_values_val\030\002 " +
      "\001(\0132\031.mojo.document.MetaValuesH\000\022\022\n\010bool" +
      "_val\030\003 \001(\010H\000\022\024\n\nstring_val\030\004 \001(\tH\000\022,\n\rda" +
      "te_time_val\030\n \001(\0132\023.mojo.core.DateTimeH\000" +
      "\022-\n\013inlines_val\030\016 \001(\0132\026.mojo.document.In" +
      "linesH\000\022+\n\nblocks_val\030\017 \001(\0132\025.mojo.docum" +
      "ent.BlocksH\000B\014\n\nmeta_valueBj\n\032org.mojola" +
      "ng.mojo.documentB\rDocumentProtoP\001Z;githu" +
      "b.com/mojo-lang/document/go/pkg/mojo/doc" +
      "ument;documentb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojolang.mojo.core.TimeProto.getDescriptor(),
          org.mojolang.mojo.core.UrlProto.getDescriptor(),
          org.mojolang.mojo.document.AttributeProto.getDescriptor(),
        });
    internal_static_mojo_document_Document_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_document_Document_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_Document_descriptor,
        new java.lang.String[] { "MetaData", "Blocks", });
    internal_static_mojo_document_Block_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mojo_document_Block_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_Block_descriptor,
        new java.lang.String[] { "Plain", "Paragraph", "LineBlock", "CodeBlock", "QuoteBlock", "OrderedList", "BulletList", "DefinitionList", "Header", "Table", "Division", "Block", });
    internal_static_mojo_document_Line_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_mojo_document_Line_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_Line_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_mojo_document_Plain_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_mojo_document_Plain_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_Plain_descriptor,
        new java.lang.String[] { "Inlines", });
    internal_static_mojo_document_Paragraph_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_mojo_document_Paragraph_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_Paragraph_descriptor,
        new java.lang.String[] { "Inlines", });
    internal_static_mojo_document_LineBlock_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_mojo_document_LineBlock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_LineBlock_descriptor,
        new java.lang.String[] { "Lines", });
    internal_static_mojo_document_CodeBlock_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_mojo_document_CodeBlock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_CodeBlock_descriptor,
        new java.lang.String[] { "Attribute", "Language", "Lines", });
    internal_static_mojo_document_QuoteBlock_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_mojo_document_QuoteBlock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_QuoteBlock_descriptor,
        new java.lang.String[] { "Blocks", });
    internal_static_mojo_document_ListAttribute_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_mojo_document_ListAttribute_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_ListAttribute_descriptor,
        new java.lang.String[] { "BeginNumber", "NumberStyle", "NumberDelimiter", });
    internal_static_mojo_document_OrderedList_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_mojo_document_OrderedList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_OrderedList_descriptor,
        new java.lang.String[] { "Attribute", "Items", });
    internal_static_mojo_document_OrderedList_Blocks_descriptor =
      internal_static_mojo_document_OrderedList_descriptor.getNestedTypes().get(0);
    internal_static_mojo_document_OrderedList_Blocks_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_OrderedList_Blocks_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_mojo_document_BulletList_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_mojo_document_BulletList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_BulletList_descriptor,
        new java.lang.String[] { "Items", });
    internal_static_mojo_document_BulletList_Blocks_descriptor =
      internal_static_mojo_document_BulletList_descriptor.getNestedTypes().get(0);
    internal_static_mojo_document_BulletList_Blocks_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_BulletList_Blocks_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_mojo_document_DefinitionList_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_mojo_document_DefinitionList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_DefinitionList_descriptor,
        new java.lang.String[] { "Items", });
    internal_static_mojo_document_DefinitionList_Item_descriptor =
      internal_static_mojo_document_DefinitionList_descriptor.getNestedTypes().get(0);
    internal_static_mojo_document_DefinitionList_Item_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_DefinitionList_Item_descriptor,
        new java.lang.String[] { "Term", "Definitions", });
    internal_static_mojo_document_Header_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_mojo_document_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_Header_descriptor,
        new java.lang.String[] { "Attribute", "Level", "Text", });
    internal_static_mojo_document_Table_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_mojo_document_Table_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_Table_descriptor,
        new java.lang.String[] { "Caption", "Alignment", "Width", "Header", "Rows", });
    internal_static_mojo_document_Table_Cell_descriptor =
      internal_static_mojo_document_Table_descriptor.getNestedTypes().get(0);
    internal_static_mojo_document_Table_Cell_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_Table_Cell_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_mojo_document_Table_Row_descriptor =
      internal_static_mojo_document_Table_descriptor.getNestedTypes().get(1);
    internal_static_mojo_document_Table_Row_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_Table_Row_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_mojo_document_Table_Header_descriptor =
      internal_static_mojo_document_Table_descriptor.getNestedTypes().get(2);
    internal_static_mojo_document_Table_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_Table_Header_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_mojo_document_Division_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_mojo_document_Division_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_Division_descriptor,
        new java.lang.String[] { "Attribute", "Content", });
    internal_static_mojo_document_Blocks_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_mojo_document_Blocks_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_Blocks_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_mojo_document_Inline_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_mojo_document_Inline_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_Inline_descriptor,
        new java.lang.String[] { "Text", "Emphasized", "Strong", "Strikeout", "Superscript", "Subscript", "SmallCaps", "Quoted", "Cite", "Code", "Space", "LineBreak", "Link", "Image", "Note", "Span", "Inline", });
    internal_static_mojo_document_Text_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_mojo_document_Text_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_Text_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_mojo_document_Emphasized_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_mojo_document_Emphasized_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_Emphasized_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_mojo_document_Strong_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_mojo_document_Strong_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_Strong_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_mojo_document_Strikeout_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_mojo_document_Strikeout_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_Strikeout_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_mojo_document_Superscript_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_mojo_document_Superscript_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_Superscript_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_mojo_document_Subscript_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_mojo_document_Subscript_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_Subscript_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_mojo_document_SmallCaps_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_mojo_document_SmallCaps_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_SmallCaps_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_mojo_document_Space_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_mojo_document_Space_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_Space_descriptor,
        new java.lang.String[] { });
    internal_static_mojo_document_LineBreak_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_mojo_document_LineBreak_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_LineBreak_descriptor,
        new java.lang.String[] { });
    internal_static_mojo_document_Note_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_mojo_document_Note_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_Note_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_mojo_document_Quoted_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_mojo_document_Quoted_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_Quoted_descriptor,
        new java.lang.String[] { "Type", "Text", });
    internal_static_mojo_document_Cite_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_mojo_document_Cite_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_Cite_descriptor,
        new java.lang.String[] { "Citations", "Inlines", });
    internal_static_mojo_document_Citation_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_mojo_document_Citation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_Citation_descriptor,
        new java.lang.String[] { "Id", "Prefix", "Suffix", "Mode", "NoteCount", "Hash", });
    internal_static_mojo_document_Code_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_mojo_document_Code_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_Code_descriptor,
        new java.lang.String[] { "Attribute", "Content", });
    internal_static_mojo_document_Link_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_mojo_document_Link_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_Link_descriptor,
        new java.lang.String[] { "Attribute", "Description", "Target", });
    internal_static_mojo_document_Image_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_mojo_document_Image_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_Image_descriptor,
        new java.lang.String[] { "Attribute", "Description", "Target", });
    internal_static_mojo_document_Span_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_mojo_document_Span_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_Span_descriptor,
        new java.lang.String[] { "Attribute", "Inlines", });
    internal_static_mojo_document_Target_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_mojo_document_Target_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_Target_descriptor,
        new java.lang.String[] { "Title", "Url", });
    internal_static_mojo_document_Inlines_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_mojo_document_Inlines_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_Inlines_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_mojo_document_MetaData_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_mojo_document_MetaData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_MetaData_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_mojo_document_MetaData_ValuesEntry_descriptor =
      internal_static_mojo_document_MetaData_descriptor.getNestedTypes().get(0);
    internal_static_mojo_document_MetaData_ValuesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_MetaData_ValuesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_mojo_document_MetaValueObject_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_mojo_document_MetaValueObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_MetaValueObject_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_mojo_document_MetaValueObject_ValuesEntry_descriptor =
      internal_static_mojo_document_MetaValueObject_descriptor.getNestedTypes().get(0);
    internal_static_mojo_document_MetaValueObject_ValuesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_MetaValueObject_ValuesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_mojo_document_MetaValues_descriptor =
      getDescriptor().getMessageTypes().get(38);
    internal_static_mojo_document_MetaValues_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_MetaValues_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_mojo_document_MetaValue_descriptor =
      getDescriptor().getMessageTypes().get(39);
    internal_static_mojo_document_MetaValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_document_MetaValue_descriptor,
        new java.lang.String[] { "MetaValueObjectVal", "MetaValuesVal", "BoolVal", "StringVal", "DateTimeVal", "InlinesVal", "BlocksVal", "MetaValue", });
    org.mojolang.mojo.core.TimeProto.getDescriptor();
    org.mojolang.mojo.core.UrlProto.getDescriptor();
    org.mojolang.mojo.document.AttributeProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
