// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/document/document.proto

package org.mojolang.mojo.document;

/**
 * Protobuf type {@code mojo.document.Header}
 */
public final class Header extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mojo.document.Header)
    HeaderOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Header.newBuilder() to construct.
  private Header(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Header() {
    text_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Header();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Header(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.mojolang.mojo.document.Attribute.Builder subBuilder = null;
            if (attribute_ != null) {
              subBuilder = attribute_.toBuilder();
            }
            attribute_ = input.readMessage(org.mojolang.mojo.document.Attribute.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(attribute_);
              attribute_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {

            level_ = input.readInt64();
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              text_ = new java.util.ArrayList<org.mojolang.mojo.document.Inline>();
              mutable_bitField0_ |= 0x00000001;
            }
            text_.add(
                input.readMessage(org.mojolang.mojo.document.Inline.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        text_ = java.util.Collections.unmodifiableList(text_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.mojolang.mojo.document.DocumentProto.internal_static_mojo_document_Header_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.mojolang.mojo.document.DocumentProto.internal_static_mojo_document_Header_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.mojolang.mojo.document.Header.class, org.mojolang.mojo.document.Header.Builder.class);
  }

  public static final int ATTRIBUTE_FIELD_NUMBER = 1;
  private org.mojolang.mojo.document.Attribute attribute_;
  /**
   * <code>.mojo.document.Attribute attribute = 1;</code>
   * @return Whether the attribute field is set.
   */
  @java.lang.Override
  public boolean hasAttribute() {
    return attribute_ != null;
  }
  /**
   * <code>.mojo.document.Attribute attribute = 1;</code>
   * @return The attribute.
   */
  @java.lang.Override
  public org.mojolang.mojo.document.Attribute getAttribute() {
    return attribute_ == null ? org.mojolang.mojo.document.Attribute.getDefaultInstance() : attribute_;
  }
  /**
   * <code>.mojo.document.Attribute attribute = 1;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.document.AttributeOrBuilder getAttributeOrBuilder() {
    return getAttribute();
  }

  public static final int LEVEL_FIELD_NUMBER = 2;
  private long level_;
  /**
   * <code>int64 level = 2;</code>
   * @return The level.
   */
  @java.lang.Override
  public long getLevel() {
    return level_;
  }

  public static final int TEXT_FIELD_NUMBER = 3;
  private java.util.List<org.mojolang.mojo.document.Inline> text_;
  /**
   * <code>repeated .mojo.document.Inline text = 3;</code>
   */
  @java.lang.Override
  public java.util.List<org.mojolang.mojo.document.Inline> getTextList() {
    return text_;
  }
  /**
   * <code>repeated .mojo.document.Inline text = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.mojolang.mojo.document.InlineOrBuilder> 
      getTextOrBuilderList() {
    return text_;
  }
  /**
   * <code>repeated .mojo.document.Inline text = 3;</code>
   */
  @java.lang.Override
  public int getTextCount() {
    return text_.size();
  }
  /**
   * <code>repeated .mojo.document.Inline text = 3;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.document.Inline getText(int index) {
    return text_.get(index);
  }
  /**
   * <code>repeated .mojo.document.Inline text = 3;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.document.InlineOrBuilder getTextOrBuilder(
      int index) {
    return text_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (attribute_ != null) {
      output.writeMessage(1, getAttribute());
    }
    if (level_ != 0L) {
      output.writeInt64(2, level_);
    }
    for (int i = 0; i < text_.size(); i++) {
      output.writeMessage(3, text_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (attribute_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getAttribute());
    }
    if (level_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, level_);
    }
    for (int i = 0; i < text_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, text_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.mojolang.mojo.document.Header)) {
      return super.equals(obj);
    }
    org.mojolang.mojo.document.Header other = (org.mojolang.mojo.document.Header) obj;

    if (hasAttribute() != other.hasAttribute()) return false;
    if (hasAttribute()) {
      if (!getAttribute()
          .equals(other.getAttribute())) return false;
    }
    if (getLevel()
        != other.getLevel()) return false;
    if (!getTextList()
        .equals(other.getTextList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAttribute()) {
      hash = (37 * hash) + ATTRIBUTE_FIELD_NUMBER;
      hash = (53 * hash) + getAttribute().hashCode();
    }
    hash = (37 * hash) + LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLevel());
    if (getTextCount() > 0) {
      hash = (37 * hash) + TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getTextList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.mojolang.mojo.document.Header parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.document.Header parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.document.Header parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.document.Header parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.document.Header parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.document.Header parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.document.Header parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.document.Header parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.document.Header parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.document.Header parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.document.Header parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.document.Header parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.mojolang.mojo.document.Header prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mojo.document.Header}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mojo.document.Header)
      org.mojolang.mojo.document.HeaderOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mojolang.mojo.document.DocumentProto.internal_static_mojo_document_Header_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mojolang.mojo.document.DocumentProto.internal_static_mojo_document_Header_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mojolang.mojo.document.Header.class, org.mojolang.mojo.document.Header.Builder.class);
    }

    // Construct using org.mojolang.mojo.document.Header.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTextFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (attributeBuilder_ == null) {
        attribute_ = null;
      } else {
        attribute_ = null;
        attributeBuilder_ = null;
      }
      level_ = 0L;

      if (textBuilder_ == null) {
        text_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        textBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.mojolang.mojo.document.DocumentProto.internal_static_mojo_document_Header_descriptor;
    }

    @java.lang.Override
    public org.mojolang.mojo.document.Header getDefaultInstanceForType() {
      return org.mojolang.mojo.document.Header.getDefaultInstance();
    }

    @java.lang.Override
    public org.mojolang.mojo.document.Header build() {
      org.mojolang.mojo.document.Header result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.mojolang.mojo.document.Header buildPartial() {
      org.mojolang.mojo.document.Header result = new org.mojolang.mojo.document.Header(this);
      int from_bitField0_ = bitField0_;
      if (attributeBuilder_ == null) {
        result.attribute_ = attribute_;
      } else {
        result.attribute_ = attributeBuilder_.build();
      }
      result.level_ = level_;
      if (textBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          text_ = java.util.Collections.unmodifiableList(text_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.text_ = text_;
      } else {
        result.text_ = textBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.mojolang.mojo.document.Header) {
        return mergeFrom((org.mojolang.mojo.document.Header)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.mojolang.mojo.document.Header other) {
      if (other == org.mojolang.mojo.document.Header.getDefaultInstance()) return this;
      if (other.hasAttribute()) {
        mergeAttribute(other.getAttribute());
      }
      if (other.getLevel() != 0L) {
        setLevel(other.getLevel());
      }
      if (textBuilder_ == null) {
        if (!other.text_.isEmpty()) {
          if (text_.isEmpty()) {
            text_ = other.text_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTextIsMutable();
            text_.addAll(other.text_);
          }
          onChanged();
        }
      } else {
        if (!other.text_.isEmpty()) {
          if (textBuilder_.isEmpty()) {
            textBuilder_.dispose();
            textBuilder_ = null;
            text_ = other.text_;
            bitField0_ = (bitField0_ & ~0x00000001);
            textBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTextFieldBuilder() : null;
          } else {
            textBuilder_.addAllMessages(other.text_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.mojolang.mojo.document.Header parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.mojolang.mojo.document.Header) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private org.mojolang.mojo.document.Attribute attribute_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.document.Attribute, org.mojolang.mojo.document.Attribute.Builder, org.mojolang.mojo.document.AttributeOrBuilder> attributeBuilder_;
    /**
     * <code>.mojo.document.Attribute attribute = 1;</code>
     * @return Whether the attribute field is set.
     */
    public boolean hasAttribute() {
      return attributeBuilder_ != null || attribute_ != null;
    }
    /**
     * <code>.mojo.document.Attribute attribute = 1;</code>
     * @return The attribute.
     */
    public org.mojolang.mojo.document.Attribute getAttribute() {
      if (attributeBuilder_ == null) {
        return attribute_ == null ? org.mojolang.mojo.document.Attribute.getDefaultInstance() : attribute_;
      } else {
        return attributeBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.document.Attribute attribute = 1;</code>
     */
    public Builder setAttribute(org.mojolang.mojo.document.Attribute value) {
      if (attributeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        attribute_ = value;
        onChanged();
      } else {
        attributeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.mojo.document.Attribute attribute = 1;</code>
     */
    public Builder setAttribute(
        org.mojolang.mojo.document.Attribute.Builder builderForValue) {
      if (attributeBuilder_ == null) {
        attribute_ = builderForValue.build();
        onChanged();
      } else {
        attributeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.mojo.document.Attribute attribute = 1;</code>
     */
    public Builder mergeAttribute(org.mojolang.mojo.document.Attribute value) {
      if (attributeBuilder_ == null) {
        if (attribute_ != null) {
          attribute_ =
            org.mojolang.mojo.document.Attribute.newBuilder(attribute_).mergeFrom(value).buildPartial();
        } else {
          attribute_ = value;
        }
        onChanged();
      } else {
        attributeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.mojo.document.Attribute attribute = 1;</code>
     */
    public Builder clearAttribute() {
      if (attributeBuilder_ == null) {
        attribute_ = null;
        onChanged();
      } else {
        attribute_ = null;
        attributeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.mojo.document.Attribute attribute = 1;</code>
     */
    public org.mojolang.mojo.document.Attribute.Builder getAttributeBuilder() {
      
      onChanged();
      return getAttributeFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.document.Attribute attribute = 1;</code>
     */
    public org.mojolang.mojo.document.AttributeOrBuilder getAttributeOrBuilder() {
      if (attributeBuilder_ != null) {
        return attributeBuilder_.getMessageOrBuilder();
      } else {
        return attribute_ == null ?
            org.mojolang.mojo.document.Attribute.getDefaultInstance() : attribute_;
      }
    }
    /**
     * <code>.mojo.document.Attribute attribute = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.document.Attribute, org.mojolang.mojo.document.Attribute.Builder, org.mojolang.mojo.document.AttributeOrBuilder> 
        getAttributeFieldBuilder() {
      if (attributeBuilder_ == null) {
        attributeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.document.Attribute, org.mojolang.mojo.document.Attribute.Builder, org.mojolang.mojo.document.AttributeOrBuilder>(
                getAttribute(),
                getParentForChildren(),
                isClean());
        attribute_ = null;
      }
      return attributeBuilder_;
    }

    private long level_ ;
    /**
     * <code>int64 level = 2;</code>
     * @return The level.
     */
    @java.lang.Override
    public long getLevel() {
      return level_;
    }
    /**
     * <code>int64 level = 2;</code>
     * @param value The level to set.
     * @return This builder for chaining.
     */
    public Builder setLevel(long value) {
      
      level_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 level = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLevel() {
      
      level_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<org.mojolang.mojo.document.Inline> text_ =
      java.util.Collections.emptyList();
    private void ensureTextIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        text_ = new java.util.ArrayList<org.mojolang.mojo.document.Inline>(text_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.mojolang.mojo.document.Inline, org.mojolang.mojo.document.Inline.Builder, org.mojolang.mojo.document.InlineOrBuilder> textBuilder_;

    /**
     * <code>repeated .mojo.document.Inline text = 3;</code>
     */
    public java.util.List<org.mojolang.mojo.document.Inline> getTextList() {
      if (textBuilder_ == null) {
        return java.util.Collections.unmodifiableList(text_);
      } else {
        return textBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .mojo.document.Inline text = 3;</code>
     */
    public int getTextCount() {
      if (textBuilder_ == null) {
        return text_.size();
      } else {
        return textBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .mojo.document.Inline text = 3;</code>
     */
    public org.mojolang.mojo.document.Inline getText(int index) {
      if (textBuilder_ == null) {
        return text_.get(index);
      } else {
        return textBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .mojo.document.Inline text = 3;</code>
     */
    public Builder setText(
        int index, org.mojolang.mojo.document.Inline value) {
      if (textBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTextIsMutable();
        text_.set(index, value);
        onChanged();
      } else {
        textBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.document.Inline text = 3;</code>
     */
    public Builder setText(
        int index, org.mojolang.mojo.document.Inline.Builder builderForValue) {
      if (textBuilder_ == null) {
        ensureTextIsMutable();
        text_.set(index, builderForValue.build());
        onChanged();
      } else {
        textBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mojo.document.Inline text = 3;</code>
     */
    public Builder addText(org.mojolang.mojo.document.Inline value) {
      if (textBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTextIsMutable();
        text_.add(value);
        onChanged();
      } else {
        textBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.document.Inline text = 3;</code>
     */
    public Builder addText(
        int index, org.mojolang.mojo.document.Inline value) {
      if (textBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTextIsMutable();
        text_.add(index, value);
        onChanged();
      } else {
        textBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.document.Inline text = 3;</code>
     */
    public Builder addText(
        org.mojolang.mojo.document.Inline.Builder builderForValue) {
      if (textBuilder_ == null) {
        ensureTextIsMutable();
        text_.add(builderForValue.build());
        onChanged();
      } else {
        textBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mojo.document.Inline text = 3;</code>
     */
    public Builder addText(
        int index, org.mojolang.mojo.document.Inline.Builder builderForValue) {
      if (textBuilder_ == null) {
        ensureTextIsMutable();
        text_.add(index, builderForValue.build());
        onChanged();
      } else {
        textBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mojo.document.Inline text = 3;</code>
     */
    public Builder addAllText(
        java.lang.Iterable<? extends org.mojolang.mojo.document.Inline> values) {
      if (textBuilder_ == null) {
        ensureTextIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, text_);
        onChanged();
      } else {
        textBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.document.Inline text = 3;</code>
     */
    public Builder clearText() {
      if (textBuilder_ == null) {
        text_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        textBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .mojo.document.Inline text = 3;</code>
     */
    public Builder removeText(int index) {
      if (textBuilder_ == null) {
        ensureTextIsMutable();
        text_.remove(index);
        onChanged();
      } else {
        textBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.document.Inline text = 3;</code>
     */
    public org.mojolang.mojo.document.Inline.Builder getTextBuilder(
        int index) {
      return getTextFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .mojo.document.Inline text = 3;</code>
     */
    public org.mojolang.mojo.document.InlineOrBuilder getTextOrBuilder(
        int index) {
      if (textBuilder_ == null) {
        return text_.get(index);  } else {
        return textBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .mojo.document.Inline text = 3;</code>
     */
    public java.util.List<? extends org.mojolang.mojo.document.InlineOrBuilder> 
         getTextOrBuilderList() {
      if (textBuilder_ != null) {
        return textBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(text_);
      }
    }
    /**
     * <code>repeated .mojo.document.Inline text = 3;</code>
     */
    public org.mojolang.mojo.document.Inline.Builder addTextBuilder() {
      return getTextFieldBuilder().addBuilder(
          org.mojolang.mojo.document.Inline.getDefaultInstance());
    }
    /**
     * <code>repeated .mojo.document.Inline text = 3;</code>
     */
    public org.mojolang.mojo.document.Inline.Builder addTextBuilder(
        int index) {
      return getTextFieldBuilder().addBuilder(
          index, org.mojolang.mojo.document.Inline.getDefaultInstance());
    }
    /**
     * <code>repeated .mojo.document.Inline text = 3;</code>
     */
    public java.util.List<org.mojolang.mojo.document.Inline.Builder> 
         getTextBuilderList() {
      return getTextFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.mojolang.mojo.document.Inline, org.mojolang.mojo.document.Inline.Builder, org.mojolang.mojo.document.InlineOrBuilder> 
        getTextFieldBuilder() {
      if (textBuilder_ == null) {
        textBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.mojolang.mojo.document.Inline, org.mojolang.mojo.document.Inline.Builder, org.mojolang.mojo.document.InlineOrBuilder>(
                text_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        text_ = null;
      }
      return textBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mojo.document.Header)
  }

  // @@protoc_insertion_point(class_scope:mojo.document.Header)
  private static final org.mojolang.mojo.document.Header DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.mojolang.mojo.document.Header();
  }

  public static org.mojolang.mojo.document.Header getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Header>
      PARSER = new com.google.protobuf.AbstractParser<Header>() {
    @java.lang.Override
    public Header parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Header(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Header> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Header> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.mojolang.mojo.document.Header getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

