// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/document/document.proto

package org.mojolang.mojo.document;

public interface LineOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.document.Line)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .mojo.document.Inline values = 1;</code>
   */
  java.util.List<org.mojolang.mojo.document.Inline> 
      getValuesList();
  /**
   * <code>repeated .mojo.document.Inline values = 1;</code>
   */
  org.mojolang.mojo.document.Inline getValues(int index);
  /**
   * <code>repeated .mojo.document.Inline values = 1;</code>
   */
  int getValuesCount();
  /**
   * <code>repeated .mojo.document.Inline values = 1;</code>
   */
  java.util.List<? extends org.mojolang.mojo.document.InlineOrBuilder> 
      getValuesOrBuilderList();
  /**
   * <code>repeated .mojo.document.Inline values = 1;</code>
   */
  org.mojolang.mojo.document.InlineOrBuilder getValuesOrBuilder(
      int index);
}
