// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/document/document.proto

package org.mojolang.mojo.document;

public interface MetaValuesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.document.MetaValues)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .mojo.document.MetaValue values = 1;</code>
   */
  java.util.List<org.mojolang.mojo.document.MetaValue> 
      getValuesList();
  /**
   * <code>repeated .mojo.document.MetaValue values = 1;</code>
   */
  org.mojolang.mojo.document.MetaValue getValues(int index);
  /**
   * <code>repeated .mojo.document.MetaValue values = 1;</code>
   */
  int getValuesCount();
  /**
   * <code>repeated .mojo.document.MetaValue values = 1;</code>
   */
  java.util.List<? extends org.mojolang.mojo.document.MetaValueOrBuilder> 
      getValuesOrBuilderList();
  /**
   * <code>repeated .mojo.document.MetaValue values = 1;</code>
   */
  org.mojolang.mojo.document.MetaValueOrBuilder getValuesOrBuilder(
      int index);
}
