// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/document/document.proto

package org.mojolang.mojo.document;

public interface MetaValueObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.document.MetaValueObject)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .mojo.document.MetaValue&gt; values = 1;</code>
   */
  int getValuesCount();
  /**
   * <code>map&lt;string, .mojo.document.MetaValue&gt; values = 1;</code>
   */
  boolean containsValues(
      java.lang.String key);
  /**
   * Use {@link #getValuesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, org.mojolang.mojo.document.MetaValue>
  getValues();
  /**
   * <code>map&lt;string, .mojo.document.MetaValue&gt; values = 1;</code>
   */
  java.util.Map<java.lang.String, org.mojolang.mojo.document.MetaValue>
  getValuesMap();
  /**
   * <code>map&lt;string, .mojo.document.MetaValue&gt; values = 1;</code>
   */

  org.mojolang.mojo.document.MetaValue getValuesOrDefault(
      java.lang.String key,
      org.mojolang.mojo.document.MetaValue defaultValue);
  /**
   * <code>map&lt;string, .mojo.document.MetaValue&gt; values = 1;</code>
   */

  org.mojolang.mojo.document.MetaValue getValuesOrThrow(
      java.lang.String key);
}
